### ISSUE TITLE
4桁パスワードタスクの導入

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#101]
実験環境：IOS（iPhone6S)，端末OS:Safari　

https://wasedasai.magcruise.org/2016/wasedasai.html
Safariからアクセス
「アプリへ」をクリック

≪手順≫
（ID:わせ1号　で登録）
コース選択で「Waseda　早稲田大学」
category-1
subcategory-1-2
PCルーム
を選択
↓
「ここに行く」を選択
コンパス付き画面＋オレンジ色の「チェックイン」を押す
QRコードを撮影する、を選択
写真を撮る、を選択　（QRコードの写真を撮る）
チェックインする　が押せる状態になる
「チェックインに成功しました！」が表示され、クイズが出る
こたえを入力して「解答」
「タスクを完了しました！」→OKボタンを押す
↓
category-1
subcategory-1-2
PCルーム
が未訪問済チェックポイントから消えていることを確認
↓
右上のメニューボタンから、「訪問済チェックポイント」を選択
PCルームが表示されている
獲得ポイントは、2/4　が表示されている

ここまでひととおり、検証ができました。

==================

QRコードですが、読み取りが時々不安定です。
decodedqr.jpg 
を紙にプリントし、これを、
「QRコードを撮影する」→「写真を撮る」　（QRコードの写真を撮る）
の読み取り対象として、Phone6Sで読ませています。

上手くいくときもありますが、やや不安定で、しばしば以下の画面がでます。
![qr_test](https://cloud.githubusercontent.com/assets/3695783/19218630/cc4a04c6-8e39-11e6-96eb-8d14a039f6de.PNG)

今後継続的にチェックしていきます。

**Comment by reikohishiyama** [comment]
やはり、QRコードの読み取り解析は、かなり不安定。
照度、画像内のQRコードの大きさ、元のQRコードの紙ベースの凹凸等からくるゆがみ、など
何かの条件に依存する？

**Comment by reikohishiyama** [comment]
QRコードリーダー、というか、QRコードユーティリティ、というか、そういうののほうが、安定している状態。
スマホのアプリの、QRコードリーダーからなら、確実にコードを読める。

**Comment by ayakix** [comment]
@reikohishiyama ご情報ありがとうございます。これ結構どうしようもないかもです。おっしゃる通りで、環境要因がかなり大きいですね。

QRコードリーダーの場合、連続してコマ撮りしてどれか一つでも解析できればOKなので、読み取れる試行回数が上がると想定できます。

読み込めない場合は、外部QRコードリーダーで読み込んだ値を入力してもらうとかかもですね。

**Comment by yuu-nkjm** [comment]
@reikohishiyama @ayakix 
あとはQRコードを使うのを止めるかですね．QRコードを使わないとすると，答を知っていた場合，移動しなくても簡単にチェックインできちゃうんですよね．

**Comment by yuu-nkjm** [comment]
「外部のQRコードリーダーを使う or 看板に書いておく or スタッフが口頭で伝える」しかなさそうですね．追加でできることとしては，lat, lonがある範囲にないとチェックインできないようにする，ぐらいですね．早稲田祭の場合は，範囲が狭いかつ屋内も多いので，GPSによる制限も有効でなさそうです．

**Comment by reikohishiyama** [comment]
今、テストしている早稲田大学（waseda.json）の中に、
以下のようなチェックイン＋テキスト入力方式で解答を求めるタスクがあります。

{
	"checkin": {
		"answerIndexes": [],
		"answerQr": "decodedqr",
		"answerTexts": [],
		"id": "sake-checkin",
		"imgSrc": null,
		"label": "QRコードを撮って下さい．",
		"point": 2.0,
		"selections": [],
		"taskType": "QrCodeTask"
	},
	"id": "sake",
	"label": "酒のタスクがあるよ",
	"lat": 35.7059,
	"lon": 139.7080833,
	"name": "sake",
	"task": {
		"answerIndexes": [],
		"answerQr": null,
		"answerTexts": [
			"宝",
			"黄桜",
			"月桂冠",
			"キンシ正宗"
		],
		"id": "sake-description",
		"imgSrc": null,
		"label": "伏見の大手酒造メーカーを一つ挙げて下さい。",
		"point": 2.0,
		"selections": [],
		"taskType": "DescriptionTask"
	}


上の、キーワード形式の入力タスクと類似したイメージで、
QRコードを利用せず、特定のキーワードを入れる形式のチェックインは、難しいでしょうか...

流れとしては、（現状では、QRコードが解析できないので）

QRコードの代わりに、キーワードを書いたボードを置いておく
↓
参加者は、チェックインスポットにたどり着いたら、そこでキーワードを、その場で入力
↓
「チェックインする」ボタンを押す

という方策です。

**Comment by yuu-nkjm** [comment]
@reikohishiyama @ayakix @ieiri0104 

チェックインは合い言葉にしましょう．以下の形式でお願いします．

```jason
"content": {
	"instanceClass": "org.magcruise.citywalk.model.task.DescriptionTask",
		"checkin": true,
		"point": 2.0,
	"label": "合い言葉を半角数字で入力して下さい．",
	"answerTexts": [
		"1111"
	]
}
```

検討が必要なのは以下のあたりです．クライアント側で採点ができるはずなので，
answerが間違っていたらリトライということもできるはずです．

- 表記揺れを防ぐために4桁半角数字のみにする
- チェックインを失敗したとき，再チェックインを許す？許さない？今は許さない．

**Comment by reikohishiyama** [comment]
@yuu-nkjm  ありがとうございます！それが安全だと思いますので、宜しくお願いします。
@ieiri0104 合言葉は、をこちらで考えて（数字のみ）、入れしまいましょう。（早稲田祭スタッフに問い合わせていると、意思決定に時間がかかって間に合わないので、こちらで決める）

**Comment by ieiri0104** [comment]
@reikohishiyama 先生
了解しました。
早稲田祭側には、そのように伝えておきます。
ありがとうございます。

**Comment by reikohishiyama** [comment]
@ieiri0104 理工（実験用）のは、とりあえず、まず暫定的に2種類の4ケタ半角数字番号を決めて、
すべてのチェックポイントについて、そのいずれかの番号を設定してみてください。

検証用のjsonとしては、本番のようにすべて異なる番号を入れてしまうと、
番号リストを持参して歩いて都度確認して検証しなければならず大変なので、宜しくお願いします。

**Comment by yuu-nkjm** [comment]
@reikohishiyama @ieiri0104 
そうですね．検証用データとしては，``1111``か``9999``あたりの間違えない番号2種類が良いですね．
