### ISSUE TITLE
ランキング表示で個人ランクが間違っている

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#102]
実験環境：IOS（iPhone6S)，端末OS:Safari　

https://wasedasai.magcruise.org/2016/wasedasai.html
Safariからアクセス
「アプリへ」をクリック

≪手順≫
（ID:わせ1号　で登録）

わせ1号は、
PCルーム、aed1、aed5の順にチェックインし、それぞれ
２点（チェックインOK、問題間違えた、従って４点満点のところ２点獲得）、
２点（チェックインOK、問題間違えた、従って４点満点のところ２点獲得）、
２点（チェックインOK、問題間違えた、従って４点満点のところ２点獲得）

となりました。
この時、ランキングは以下のとおり。
わせ１号は６点獲得していて、合計は合ってますが、順位が３位です（泣）
hogeやぽんは、4点なのに、わせ１号より順位が上です。
ソート間違ってないでしょうか。

![image](https://cloud.githubusercontent.com/assets/3695783/19218695/ca1b2ad4-8e3b-11e6-9a28-650a6cab4e5a.png)

**Comment by ayakix** [comment]
@reikohishiyama 失礼しました。こちら調査した所、Safari on iOSにて発生する問題でした。修正しました。

ちなみに、Chrome on Androidでは問題ありませんでした。

**Comment by yuu-nkjm** [comment]
個人順位
