### ISSUE TITLE
ナビ画面で、位置情報（~m、および、自分の位置）が更新されないケース

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#103]
実験環境：IOS（iPhone6Plus)，端末OS:Safari　菱山
実験環境：IOS（iPhone5S)，端末OS:Safari　家入

利用したURL
https://wasedasai.magcruise.org/magcruise-citywalk/app/・・・・.html
（いろいろ）

「位置情報が更新されない」ケースとは、以下のとおりです。

◎正常な状態
コンパスが出ている画面で歩くと、通常は「~m」が随時更新され、自分の位置情報を示す青丸も更新される。
この更新によってナビゲートされ、チェックインポイントへ接近する。

◎問題状態
コンパスが出ている画面で歩くと、更新されていた「~m」が止まり（例えば、常に「178ｍ」から表示が更新されない状態となり、）予定されているチェックインポイントへ接近しても178ｍのままとなる。
（以下は、その更新がされなくなっている状態のスクリーンショット。下の画面の状態からチェックポイントへ接近しても、「178ｍ」の表示は更新されない。）
このとき、自分の位置情報（青丸）も表示されない。

![image](https://cloud.githubusercontent.com/assets/3695783/19219067/6e26c9d2-8e44-11e6-95e4-7c1a89fc066b.png)

◎要因（再現方法）
コンパスが出ている画面で歩いている途中で、「既に訪問したチェックポイントってどこだっけ？」と思って、コンパスが出ている画面で、右上に表示されているメニューボタンを押し、訪問済みチェックポイントの画面へ遷移する。その後、再び、「＜」（ブラウザ自体の「戻る」ボタン、画面の最も左下に出ている）を押し、コンパスが出ている画面に戻ると、この時点から、更新されていた「~m」が止まる（例えば、常に「118ｍ」から表示が更新されない）状態となる。

＃（以下は、実験していないが）
同様に、「未訪問チェックリストって他になかったっけ？」と思って、未訪問チェックポイント画面へ遷移した後、再び「＜」（ブラウザ自体の「戻る」ボタン、画面の最も左下に出ている）を押し、コンパスが出ている画面に戻っても、同じ状況かと思われる。

（参考）
コンパスが出ている画面で歩いている途中で、LINE（cityWALK以外の他のアプリ）を参照し、再びコンパスが出ている画面に戻った場合は問題なく、更新されていた「~m」が、再び更新される。

△復帰方法
位置情報の更新が止まった状態で、ブラウザのリロードボタンを押すと、また位置情報の更新ができるようになることがある。しかし、以下の画面のように、更新ができず、「画面が崩壊した状態」になることもある。
（「画面が崩壊した状態」になる場合は、iPhone6Plusでは発生しなかったが、iPhone5Sで、複数回発生した）

以下はその崩壊時のスクリーンショット２枚。
![image](https://cloud.githubusercontent.com/assets/3695783/19219096/49b1932e-8e45-11e6-94b0-afc2642b25b3.png)

![image](https://cloud.githubusercontent.com/assets/3695783/19219098/563631ea-8e45-11e6-873d-63f9bac53535.png)

**Comment by ayakix** [comment]
> 画面が崩壊した状態
CSSが読み込めていません。サーバ負荷ではないと思いますので、端末のネットワーク状態が悪いかと思います。こちらに対しては、対応の使用がありません。

GPS情報が更新されない件については、調査しますね。

**Comment by ayakix** [comment]
@reikohishiyama  こちらおそらくですが、 https://github.com/MAGCruise/magcruise-citywalk/issues/108 と同様かと思います。先のissueで対応します。
