### ISSUE TITLE
「早稲田祭について」画面、「このサービスについて」（クレジット）画面、「使い方」画面

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#105]
@ieiri0104　以下の3つの画面を作ります。

「早稲田祭について」
「このサービスについて」
「使い方」
→可能であれば、メニュー画面に追加して頂きたいのですが....いずれも特段の機能はないページです。

≪内容≫
早稲田祭について
：早稲田祭２０１６ウェブページへリンクする

このサービスについて：
（五十音順）
合同会社方痴民
東邦大学中島研
早稲田祭2016運営スタッフ  実践促進担当
早稲田大学菱山研

使い方：
このサービスの使い方を、メニュー別に整理して記述

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生

「使い方」の簡単な仕様について
Dropbox/GLearningKyoto/Ieiri/wasedasai-html
に一部ではありますがhtml,css,imgについて作成したものを置きました。

作り方としては、top.cssをもとに、fontを変更したバージョンとして、howto.cssを作成して、それをhowto.htmlに適用しております。また、imgファイルを1枚入れております。

このような書き方で継続して大丈夫かどうか、レビューしていただけたら嬉しいです。

よろしくお願いいたします。

**Comment by yuu-nkjm** [comment]
@ieiri0104 
「早稲田祭について」「このサービスについて」「使い方」を一つのページにまとめて下さい．
中身(文章+画像)に注力して下さい．見た目はこちらでやります．

**Comment by reikohishiyama** [comment]
3画面、追加して頂いて、ありがとうございます！

引き続きお願いで、「アプリについて」画面で、「研究開発チーム」として、
既に、このチームの人々一覧 を入れています。
お手すきの折に、内容を覗いてみて頂けたら嬉しいです。

そして、もし何か変更したいことがありましたら、適宜、ご要望をお寄せください。
（名前だけで組織名いらない、とか、組織名だけでいいとか、
名前はニックネームにしたいとか、ロゴ入れたい、とか..）
何もなければこのままでいきます。

**Comment by yuu-nkjm** [comment]
内容を確認しました．
@ayakix さん，いかがでしょうか？
確認したら close して下さい．

**Comment by ayakix** [comment]
私の方でも確認いたしました。ご用意して頂きありがとうございます！

closeします。
