### ISSUE TITLE
iOSのナビ画面で残り距離が変わらない

### ISSUE THREAD

**Issue by ieiri0104** [MAGCruise/magcruise-citywalk#108]
未訪問チェックポイント一覧画面から、ナビ画面へ遷移すると、次に添付したような画像のようになってしまい、現在地（地図）、距離共に表示されない状態になってしまい、コンパスも固まってしまう時があります。また、その下にあるほかのユーザーのアクティビティ履歴は表示されております。

![img_1002 1](https://cloud.githubusercontent.com/assets/18714543/19227763/eef66fae-8ef8-11e6-8198-834803436aac.PNG)

この画面は、更新をすると正しい画面になり、現在地も距離も正しく表示されますが、移動によって距離が変化したりしなかったりな状況です。

しかし、ナビの途中でランキング画面への移動、未訪問チェックポイント一覧画面への移動などをした後に、新しく作成してくださった戻るボタンを使ってナビ画面に戻ったら、現在地、距離ともに表示はされますが、値が変化しなくなってしまい、固まってしまいます。（コンパスは動いています。）この場合は、更新ボタンを押しても変化はありませんでした。

この固まった状態を打破するには、一回ブラウザを閉じてから開いたら、もとのナビ画面が出力されます。この時は正常にナビ画面が機能します。しかし、移動中に値の変化が止まってしまう時があり、この時に更新ボタンを押すと、はじめのコース選択画面に移ってしまいます。

使用したブラウザは、safari ios です。
一応chrome ios でも試しましたが、同様でした。

実験したところ、chrome アンドロイドについては、この現象は起きないようです。

safari ios 　　iphone6Plus     iphone5s     
chrome アンドロイド 5.1.1       ASUS Zenphone  ASUS_013DB  
です。

**Comment by ayakix** [comment]
ご情報ありがとうございます。Googleマップの初期化のコールバックが呼ばれないケースがありそうです。もう少し調べてみますね。

**Comment by yuu-nkjm** [comment]
@ieiri0104 君
このバグの発生頻度はどれくらいでしたか？同じ手順だと毎回固まっていましたか？
wasedasai.magcruise.orgにデプロイされているもので試して下さい．

**Comment by ieiri0104** [comment]
@yuu-nkjm先生　 @ayakixさん 

理工キャンパスで実際に再度歩いてみました。

まず、以前は「未訪問チェックポイント一覧画面から、ナビ画面へ遷移すると、次に添付したような画像のようになってしまい、現在地（地図）、距離共に表示されない状態になってしまい、コンパスも固まってしまう時があります。」という状態（issueを立てたときの画像の状態）でしたが、今回は全ての実験で「未訪問チェックポイント一覧画面から、ナビ画面へ遷移すると、現在地（地図）、距離共に表示される」という状態になった、という変化がありました。

使用するブラウザによって、再現や頻度に変化がありましたので、別々にして報告いたします。

safari iosの場合 　　iphone6Plus iphone5sで実験＜全17回＞
・未訪問チェックポイント一覧画面から、ナビ画面へ遷移した際に、現在地（地図）と距離に関しては表示されるが、値は変化しない（17回/全17回中）
・この画面でブラウザの更新ボタンを押すと、正しい画面になり、現在地も距離も正しく取得し、表示されるが、この動作を行っても、相変わらず、移動によって値が変化しない（7回/全17回中）
・ナビの途中でメニューからランキング画面や未訪問チェックポイント一覧画面を選択し、画面を遷移させる。その後、新しく作成してくださった「戻る矢印」ボタンを使ってナビ画面に戻ったら、現在地、距離ともに表示はされますが、値が変化しなくなってしまい、固まってしまう（17回/全17回中）
・この場合に、ブラウザの更新ボタンを押しても、相変わらず、移動によって値が変化しない（12回/全17回中）
・この固まった状態を打破するために、一回ブラウザを閉じ（スマホのホームボタンをダブルクリックし、複数の画面履歴の中から、止まってしまっていたsafari画面を選択し、スワイプして削除）、再度ホーム画面からsafariアプリを選択し、開いたら、もとのナビ画面が出力される。この時は正常にナビ画面が機能する。この時にブラウザの更新ボタンを押すと、必ず、はじめの「はじめに」画面に移ってしまう（17回/全17回中）

chrome アンドロイドの場合　　 5.1.1 ASUS Zenphone ASUS_013DBで実験
通信環境の影響もあり、ナビ画面での距離の値の変化は若干遅いですが、現在地（地図）と距離の値が変化せずに固まってしまう、というバグは発生しませんでした。

**Comment by yuu-nkjm** [comment]
@ieiri0104 君，ありがとう．

> ・未訪問チェックポイント一覧画面から、ナビ画面へ遷移した際に、現在地（地図）と距離に関しては表示されるが、値は変化しない（17回/全17回中）

のとき，コンパスは動くのでしょうか？

**Comment by yuu-nkjm** [comment]
@ieiri0104 
chrome on iosも試して下さい！

@ayakix 
ePos，cPosをグローバルでなく，引数渡しにしてみますか？ 
素直に考えるとePos，cPos がなぜか無効な値になってしまっているようですよね．
単なる勘ですが，参考まで．

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生
safari on iosでやってみました。結果は以下のようになっております。

コース選択画面→未訪問チェックポイント一覧
![image](https://cloud.githubusercontent.com/assets/18714543/19304857/52078ec8-90a9-11e6-96a5-5b4551ab7c1d.png)

未訪問チェックポイント一覧→ナビ画面
（以下のように、位置のログが一回だけ溜まり、それ以降のログは表示されません）
![image](https://cloud.githubusercontent.com/assets/18714543/19305086/5b8f6aaa-90aa-11e6-8e4c-9774c00b1d8d.png)

ナビ画面→チェックポイント済み一覧
![image](https://cloud.githubusercontent.com/assets/18714543/19304990/e203d5f4-90a9-11e6-91c6-5dbb69fd8f92.png)

「一回ブラウザを閉じ（スマホのホームボタンをダブルクリックし、複数の画面履歴の中から、止まってしまっていたsafari画面を選択し、スワイプして削除）、再度ホーム画面からsafariアプリを選択し、開いたときに表示されるナビ画面」→ブラウザの更新ボタンを押す→「はじめに」画面に移ってしまう
![image](https://cloud.githubusercontent.com/assets/18714543/19305007/f8f60476-90a9-11e6-94a8-e44593aa2b1b.png)

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生

・未訪問チェックポイント一覧画面から、ナビ画面へ遷移した際に、現在地（地図）と距離に関しては表示されるが、値は変化しない（17回/全17回中）
のとき，コンパスは動きます。

また、chrome on iosについてやり方を調べてみたのですが、アンドロイド版ならあるのですが、iosのやり方が出てこなく、データがとれそうにありません。申し訳ありませんが、chrome on iosのログをとる方法があれば、教えていただけないでしょうか？

**Comment by yuu-nkjm** [comment]
@ieiri0104 iPhone持ってないので分かりません．chrome on ios で動作するのかどうかだけ，まずは教えて下さい．

コンソールのスクリーンショットだけでなく，ログそのものを貼って下さい．
よろしくお願いします．

**Comment by yuu-nkjm** [comment]
@ayakix 
参考情報としては，movementは保存できていそうです．
![](https://i.gyazo.com/59fac115688f682b8a02d778908f8639.png)

**Comment by ayakix** [comment]
@reikohishiyama @yuu-nkjm @ieiri0104 
テストして頂きまして誠にありがとうございます。

こちらの問題ですが、iOS固有のバグのようです。

geolocation.watchPositionにより、位置情報を連続取得しているつもりでしたが、iOSの場合、一度呼ばれるだけで終了してしまうケースがあるらしいです。（しかもたちの悪いことに、たまにうまく連続取得できるため、リロードすると正常動作する時があった）

修正は終えたのですが、私を含めもう一度複数人でテストしたいので、テストを終えてからこのissueをクローズします。

（ちなみにこれでもダメな場合、一回だけ位置情報を取得する関数であるgeolocation.getCurrentPositionを呼び、内部でタイマーを使って再帰的に自分を呼び出し、位置情報を連続取得する手法が考えられます）

**Comment by yuu-nkjm** [comment]
@ayakix 
このバグとは直接関係なさそうですが，謎のCSSを読み込みに行ってしまっているあたりは大丈夫でしょうか？

**Comment by ayakix** [comment]
@yuu-nkjm css.mapの記述を削除しました。 https://github.com/MAGCruise/magcruise-citywalk/pull/128/commits/70964fff02e29b6286657077bf74f2bb5286ec45

ナビも問題なさそうでうので、クローズします。
