### ISSUE TITLE
＜確認＞2016/10/10版について

### ISSUE THREAD

**Issue by ieiri0104** [MAGCruise/magcruise-citywalk#109]
2016/10/10版のgitに上がっているデータをcloneして、ローカルで動かしました。
eclipseも正常に動き、問題ないように思われたのですが、「大食堂」をチェックインしたのに、それが未訪問チェックポイント一覧から消えず、訪問済みチェックポイント一覧に移らない、という問題が起こりました。

はじめ、「大食堂」でタスクを行った後、未訪問チェックポイント一覧から消えないので、再度「大食堂」へのナビ画面には遷移できるのですが、次のような画面が出てしまいます。

![image](https://cloud.githubusercontent.com/assets/18714543/19230147/dd288a22-8f0d-11e6-8fbd-0aab5e0b7832.png)

この画面では、以前に自分の行ったアクティビティの履歴が残っております。ここで「チェックイン」のボタンを押しても反応がなく、画面の遷移は行われません。

**Comment by ayakix** [comment]
@ieiri0104 こちら、`チェックインしたが、タスクは全て完了しなかった` という状況でしょうか？
それでしたら、 https://github.com/MAGCruise/magcruise-citywalk/pull/99 を御覧ください。

**Comment by ieiri0104** [comment]
@ayakix さん
説明不足で申し訳ありません。
チェックインをして、そのあとのタスクも完了させたのですが、未訪問チェックポイントから消えないという状況になっております。

**Comment by yuu-nkjm** [comment]
@ieiri0104 君
エラー報告ありがとう．エラーが起こった時の手順は正確に書いて下さい．また，JavaScriptのコンソールを開いて，エラーログ(コンソールに出力されたエラー)を取得して，それも報告して下さい．

**Comment by reikohishiyama** [comment]
菱山のPC上で、Web上の環境で確認していますが、今、大食堂が、訪問済のリストと未訪問のリストの両方に存在しています。どのように見えるかというと、以下のように、未訪問に大食堂がいて、、
![image](https://cloud.githubusercontent.com/assets/3695783/19266404/562349d6-8fe4-11e6-923b-23dc0229a050.png)

以下のように訪問済にも大食堂がいます。
![image](https://cloud.githubusercontent.com/assets/3695783/19266427/6db23990-8fe4-11e6-9fa6-5f5884839ac2.png)

手順は以下のとおり。
PC（Chrome）で、ユーザネームはhishiyama（以前にユーザネーム登録したもの）

wasedasai.magcruise.org/
にアクセスすると、自動的に
https://wasedasai.magcruise.org/2016/app/how-to-use.html
に飛ばされるので、how-to-use.html部分を消去し、
https://wasedasai.magcruise.org/2016/app/
でエンターキーでブラウザに読み込み
↓
コース選択画面で、Wsaseda 早稲田大学（一番上）を選択
↓
TOP > category-1 > subcategory-1-1
と遷移すると、大食堂がいるので、
ここに行く
↓
チェックイン
↓
適当な画像を入れてチェックイン
↓
クイズ出題
↓
クイズに解答完了
↓
この状態で、右上のオレンジ色の「メニュー」から、未訪問リストを選択して表示させると、未訪問リストに大食堂がいる。
あれ？　と思って、
と思って、右上のオレンジ色の「メニュー」から、訪問済リストを選択すると、訪問済リストに大食堂がいる、

です。

この状態になっているので、現在未訪問リストにいる大食堂を選び、「ここへ行く」を選んだ後、地図のチェックインボタンを押すと、ボタンは凹んだような色になりますが、その先の画面（チェックイン画面）には遷移しません。

もうちょっと、検証してみます。

**Comment by ayakix** [comment]
@reikohishiyama slack上で対応したいと思います。今お時間あればslackを覗いて下さい。

**Comment by ayakix** [comment]
描画時間帯機能
https://github.com/MAGCruise/magcruise-citywalk/issues/70
における下記コミットが原因と思われます。
https://github.com/MAGCruise/magcruise-citywalk/commit/245a6774684935abe5e93a16b0f0d84320d2504f

visibleTimeFromとvisibleTimeToがJSONに追加されていないのですが、それ前提のコードがmasterにマージされ、かつデプロイされています。
正直、防ぎようがありません。

@yuu-nkjm `masterにマージする＝その時点で実装されている機能は基本的に動作する。`という状態にさせてください。何かプログラムやデータが不足している場合には、ブランチのまま作業し、全ての動作確認が取れてからmasterにマージするようにしてください。デグレやバグの原因となります。何卒宜しくお願い致します。

**Comment by yuu-nkjm** [comment]
@ayaki さん，対応ありがとうございます．

https://github.com/MAGCruise/magcruise-citywalk/commit/245a6774684935abe5e93a16b0f0d84320d2504f
のコミットですが，

```
private Date visibleTimeFrom = new Date(0);
private Date visibleTimeTo = DateTimeUtils.fromTimestamp("2099-01-01 00:00:00");
```

のようになっているので，visibleTimeFromやToは指定していなくても動作します．
現在のmasterでは

wasedaは時刻指定なしなので，いつでも表示される．
wasedasaiは時刻指定ありなので，期間内しか表示されない

で正しい振る舞いになっていると思います．

;; 実際には，JSで，ToとFromの間に現在時刻が入っているかどうかのfilterの動作までしかみていなくて，
;; 本当に表示されるかどうかは見ていません

**Comment by yuu-nkjm** [comment]
@ayakix 
すみません，visibleTimeFromとToのfilterをするコードのマージをミスってました．
直します．

**Comment by yuu-nkjm** [comment]
@ayakix デグレさせててすみません．気付きませんでした．

> masterにマージする＝その時点で実装されている機能は基本的に動作する。という状態にさせてください。何かプログラムやデータが不足している場合には、ブランチのまま作業し、全ての動作確認が取れてからmasterにマージするようにしてください

基本的にはmasterには動作可能なものをpushしているつもりですが，人力だと「全ての動作確認」にミスが…．

**Comment by ayakix** [comment]
@yuu-nkjm 

> wasedaは時刻指定なしなので，いつでも表示される．
> wasedasaiは時刻指定ありなので，期間内しか表示されない
> で正しい振る舞いになっていると思います．

承知しました。

ae36024 の修正ありがとうございます。助かります。

> 基本的にはmasterには動作可能なものをpushしているつもりですが，人力だと「全ての動作確認」にミスが…．

仰るとおりですね。
（ちょっと今更感はあるのですが）作業は基本的にブランチを切り、サーバ<->クライアント間で影響しそうなものについては、プルリクエストを送り、互いにレビューという手順でいかがでしょうか。

**Comment by yuu-nkjm** [comment]
@ayakix 

> （ちょっと今更感はあるのですが）作業は基本的にブランチを切り、サーバ<->クライアント間で影響しそうなものについては、プルリクエストを送り、互いにレビューという手順でいかがでしょうか。

そうしましょう．つまらないミスで，お時間取らせてしまってすみません．
