### ISSUE TITLE
<確認>ユーザネーム(ニックネーム）の文字数制限と使用可能文字

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#111]
初期ログイン画面で入力するユーザネーム（ニックネーム）について、現在、
何か条件が設定されていたら、内容をお教え頂けたらうれしいです。
その情報を、「使い方」の画面に記述します。

（例）
【文字数制限】
1文字から10文字　
【使用可能文字】
平仮名、カタカナ、漢字、英数字（全角及び半角）、半角記号、とか

例えば、上のような条件がある場合は、その情報を（「使い方」画面に書くため）欲しいです。

文字数制限について、
あまりにも長い文字数は、画面表示上の問題を生じるのではないかと予測しており、
もし現状で長さの条件設定がされていない場合は、適宜決めて頂けるといいのかな、と
思っています。ご検討お願いします。

**Comment by yuu-nkjm** [comment]
@ayakix 
本件どうでしょう？URLにuser_idを含めなくなったのであれば，特に制限はないと思っていますが．

**Comment by ayakix** [comment]
@reikohishiyama @yuu-nkjm レイアウトが崩れるため、文字数だけ制限したいです。半角ならN文字、全角ならN/2文字等でしょうか。
N=10文字ぐらいですかね？

**Comment by yuu-nkjm** [comment]
@ayakix そうしましょう！ 使い方は僕の方で書いておきます．

inputの入力制限をお願いします．user_idのinputのラベルに「N文字以下です」までは書かなくても良いですかね．適当にお任せします．

**Comment by yuu-nkjm** [comment]
「使い方は僕の方で書いておきます」と書きましたが，inputが長すぎたときに「全角5文字(半角10文字)以下です」が表示されれば十分ですね．

**Comment by yuu-nkjm** [comment]
ひとまず「全角半角を問わず8文字以下」にしました．
