### ISSUE TITLE
未訪問チェックポイント，訪問済みチェックポイントでのアイコン表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#112]
以下のプレースホルダーを置き換え

![](https://i.gyazo.com/5a92f1ad5b19716f5d0965475fc60cff.png)
![](https://i.gyazo.com/01c159f1229b48de68f4ab6b34b38922.png)

**Comment by ayakix** [comment]
描画時間帯機能
https://github.com/MAGCruise/magcruise-citywalk/issues/70
における下記コミットが原因と思われます。
https://github.com/MAGCruise/magcruise-citywalk/commit/245a6774684935abe5e93a16b0f0d84320d2504f

visibleTimeFromとvisibleTimeToがJSONに追加されていないのですが、それ前提のコードがmasterにマージされ、かつデプロイされています。
正直、防ぎようがありません。

@yuu-nkjm `masterにマージする＝その時点で実装されている機能は基本的に動作する。`という状態にさせてください。何かプログラムやデータが不足している場合には、ブランチのまま作業し、全ての動作確認が取れてからmasterにマージするようにしてください。デグレやバグの原因となります。何卒宜しくお願い致します。

**Comment by yuu-nkjm** [comment]
@ayakix 
JSONのプロパティですが，クライアントのこれまでのコードはキャメルケースでした．今後もクライアント側はキャメルケースでお願いします．

;; Java側では，キャメルケースでもスネークケースでもJSONを読み込めますが，JavaでJSON出力するときは，
;; キャメルケースになっています．

![](https://i.gyazo.com/c8e718a6b2b5c3b96f3aa27e5a54caa0.png)

**Comment by ayakix** [comment]
> JSONのプロパティですが，クライアントのこれまでのコードはキャメルケースでした．今後もクライアント側はキャメルケースでお願いします．

承知しました。

> imgSrcが未指定の時，どうしましょう？

`placeholder.svg` を表示が楽ですね。（もちろん、プレースホルダー画像を頂ければ変更することもできます。）
ちょっとつらいのが、「imgSrcがない場合は、レイアウトの位置を変える」となります。例えば、labelやdescriptionを左詰めにする等です。

**Comment by yuu-nkjm** [comment]
なぜ，「うちわ」かはさておき，いけました．楽しげになりそうです．

![](https://i.gyazo.com/a877125fee6fe27407ede417979b2acc.png)

```js
    var imgSrc = checkpoint.imgSrc==null? "../img/placeholder.svg" : "../img/"+checkpoint.imgSrc;
```

「何らかの画像を入れる」という決まりだけ決めておきましょう．リストの見映え的にも空間を詰めるよりは，
画像を入れた方が良いと思います．

**Comment by yuu-nkjm** [comment]
@ayakix 
訪問済みの方にも組み込みました．

https://github.com/MAGCruise/magcruise-citywalk/commit/cafb05987b1ce1f5d63e0fcd0aad6f4d46eee11b
