### ISSUE TITLE
チェックポイント一覧での項目の表示内容

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#12]
提案資料にあったような記述にして欲しいです．

![](https://i.gyazo.com/f42c0a9de6d57f1706e097722ccf355d.png)

名前(name)+短い内容説明文(label)が適当でしょうか．

![](https://i.gyazo.com/20835d929a9d63daba9eddc277bea9a6.png)

checkpointにlabelは入れときましたので，描画をお願いします．

**Comment by ayakix** [comment]
追加しました。

<img width="376" alt="2016-09-25 11 55 17" src="https://cloud.githubusercontent.com/assets/907388/18812700/3381c2e2-8317-11e6-9f72-e2a0e0dfe19b.png">
