### ISSUE TITLE
10月18日の実験について

### ISSUE THREAD

**Issue by ieiri0104** [MAGCruise/magcruise-citywalk#129]
日程: 10月18日
時間: 13時15分～14時15分
場所: 早稲田本部キャンパス

**Comment by yuu-nkjm** [comment]
このプロジェクトは公開プロジェクトです．
公開して問題ない情報であれば，ここに書いてもOKです．

そうでなければ，以下に書いて下さい．

https://github.com/nkjmlab/MAGCruiseCityWalk/issues/12
