### ISSUE TITLE
訪問済みポイント確認画面へのボタン

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#13]
訪問済みポイント，バッジ，ランキングの確認などをするときのボタンを，何か良い感じにして欲しいです．

![](https://i.gyazo.com/8bd941f704e66295931ef8b5a45dd358.png)

右上の歯車だけだとちょっと目立たなすぎですかね．

![](https://i.gyazo.com/8f63ea4f7febe94fad3f4cbf830a630c.png)

のように，一番使いそうなやつは，トップに出した方がよいでしょうか．
もしくは，「これまでの行動」とか適当なラベルをつけて，歯車アイコンではなく，
オレンジボタンにする？

良いアイディアがあれば，お願いしますー

**Comment by ayakix** [comment]
<img width="295" alt="2016-09-25 12 24 45" src="https://cloud.githubusercontent.com/assets/907388/18812832/4bbffc3a-831b-11e6-800f-5b5f2aa3234d.png">

* ドロップダウンの背景色をオレンジにし目立つように
* ログアウトをリストの一番下に移動し、dividerを挟んで押し間違いを減らす
* リストアイテムの高さが足らず押しづらかったため、幅広に
