### ISSUE TITLE
その接近中のナビ画面を上へスワイプして消去し、再度、サファリのアプリのアイコンから入る時について

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#132]
本日、最新版を使って、safari iosで実験をして見たところ
あるチェックインポイントへ接近中のナビ画面が出ている状態で、ホームボタンをダブルクリックして、何枚かの画面が重なった状態になった画面で、ナビ画面を選択し、上にスワイプして消去し、再度、サファリのアプリのアイコンをクリックして入る時に以下のようになりました。

再度サファリのアプリのアイコンから入ると、ナビ画面が再び表示されるのですが、その画面から、「チェックイン」ボタンを押すと、「はじめに」画面に戻ってしまいます。同じ画面から、「チェックイン」ボタンではなく、ブラウザの更新ボタンを押した時にも、「はじめに」画面に戻ってしまいます。

**Comment by reikohishiyama** [comment]
ブラウザが消去されて、セッションが切れた時に限り、上の状態になる。

**Comment by reikohishiyama** [comment]
「セッションがタイムアウトしました」のメッセージを出すかどうかは要検討

**Comment by yuu-nkjm** [comment]
safariを再起動したとき，タブが復元される．その時の対応コードを書いた．

https://github.com/MAGCruise/magcruise-citywalk/pull/133
