### ISSUE TITLE
チェックポイントの吹き出しに表示する情報

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#134]
@ayakix 
現在，IDが表示されていると思いますが，名前とカテゴリ，サブカテゴリを表示して欲しいです．

**Comment by yuu-nkjm** [comment]
＠ayakix
ペンディングでお願いします。slackの議論まちで。

**Comment by ayakix** [comment]
@yuu-nkjm 承知しましたー。

**Comment by reikohishiyama** [comment]
ナビ画面の地図のアイコンの吹き出しですが、以下を希望しています．

（名前，カテゴリ、サブカテゴリではなく），jsonに新たに追加される要素から取得する．
jsonには、balloon として，新たな要素を追加する．
balloonに記載された情報が，地図上の吹き出しに表示される．

（例）

仕様変更が申し訳ないのですが…  如何でしょうか。

**Comment by ayakix** [comment]
@reikohishiyama こちらチェックポイント一覧画面でよろしいでしょうか？

**Comment by ayakix** [comment]
![2016-10-16 22 57 43](https://cloud.githubusercontent.com/assets/907388/19417932/18349dc8-93f4-11e6-87be-e6778d0d914e.png)

**Comment by ayakix** [comment]
![2016-10-16 23 08 11](https://cloud.githubusercontent.com/assets/907388/19417983/941389c6-93f5-11e6-9ed3-678d8cbf07dd.png)

ナビ画面にも追加しました。

**Comment by reikohishiyama** [comment]
ありがとうございました！！
イメージそのもので、コレで大丈夫です。
