### ISSUE TITLE
チェックポイントページのチェックポイント絞り込み時に再読み込みしない

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#135]
@ayakix 

markerレイヤーだけ再描画すれば軽くなると思ったけど，絞り込むと地図の中心位置変わるんですね．
カテゴリを移動するときに，少しもっさりするのが気になるところです．

**Comment by ayakix** [comment]
@yuu-nkjm 修正しました。
