### ISSUE TITLE
チェックポイントのカテゴリ分け

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#14]
チェックポイントのカテゴリ分け機能を作る．

category, sub-categoryという属性を追加する．

アコーディオン方式にするとすると，チェックポイントが登場する深さは固定の方が良いですかね．

*全てのチェックポイントにおいてcategoryがない
```
   checkpoint1
   checkpoint2
   checkpoint3
```

*全てのチェックポイントにおいてcategoryがある．(sub-categoryはない)
```
   category-name1
         checkpoint1
         checkpoint2
   category-name2
         checkpoint3
```

*全てのチェックポイントにおいてcategoryとsub-categoryがある．
```
   category-name1
         sub-category-name1
                checkpoint1
         sub-category-name2
                checkpoint2
   category-name2
         sub-category-name1
                checkpoint3
```

**Comment by ayakix** [comment]
https://github.com/MAGCruise/magcruise-citywalk/commit/29b29985af630231c8fa3227cdede1987e0807cf#diff-27aa8abc724d8d4d82bf13e0f15633daR10

**Comment by ayakix** [comment]
<img width="1193" alt="2016-09-29 21 02 15" src="https://cloud.githubusercontent.com/assets/907388/18953214/49cccb0e-8688-11e6-88be-3d1e8b4a7734.png">

@yuu-nkjm @reikohishiyama @ieiri0104 
カテゴリおよびサブカテゴリに対応しました。`category`と`subcategory`を追加して下さい。

```
{
      "id":"cafeteria",
      "lat": 35.706489,
      "lon": 139.708019,
      "name": "大食堂",
      "label": "お昼は激こみ",
      "marker_color": "red",
      "category": "category-1",
      "subcategory": "subcategory-1-1",
      "checkpoint_group_ids": ["waseda"]
    },
```

カテゴリ一覧→サブカテゴリ一覧と進んだ際に、戻るUIが必要になるかと思うのですが、スクリーンショットにあるように、パンくずリストを表示しています。`TOP>カテゴリ>サブカテゴリ`
