### ISSUE TITLE
ナビ画面でのチェックポイント情報の表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#140]
@ieiri0104  @reikohishiyama 
ナビ画面でのチェックポイント情報を増やす？

labelの内容は，ナビ画面でも表示できた方がよいと思います．チェックポイント画面で見られた情報をナビ画面で見られないと，「戻る」ボタンが押されやすいと思うので．

descriptionは，チェックインしてからしか見られませんが，その前にも見られた方が良いと思います．

いかがでしょうか？

**Comment by reikohishiyama** [comment]
はい、スペースと配置に問題ないようでしたら、それでお願いします！

**Comment by yuu-nkjm** [comment]
@ayakix 
地図とXXXでのアクティビティの間あたりでしょうか？ labelとdescriptionの内容を記載願います．
```
name (あってもなくても良いと思います．)
label
description
```

**Comment by yuu-nkjm** [comment]
以下のように修正した．

![](https://i.gyazo.com/5616e5b7be2a47b19175481e18df70a4.png)

**Comment by ayakix** [comment]
@yuu-nkjm こちら対応が遅れまして大変申し訳ありません。また、修正して頂きありがとうございます。
