### ISSUE TITLE
ナビ画面でのバルーン表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#141]
@ayakix 
すみません，チェックポイント画面でのバルーン表示を，ナビ画面でも追加してもらえないでしょうか．
チェックポイント画面で見られた情報をナビ画面で見られないと，「戻る」ボタンが押されやすいと思うので．

よろしくお願いします．

https://github.com/MAGCruise/magcruise-citywalk/pull/139

**Comment by yuu-nkjm** [comment]
https://github.com/MAGCruise/magcruise-citywalk/pull/139

**Comment by ayakix** [comment]
@yuu-nkjm 
https://github.com/MAGCruise/magcruise-citywalk/issues/134#issuecomment-254049149

バルーンを表示するということでしょうか。それでしたらこちらで対応済みです。

**Comment by yuu-nkjm** [comment]
@ayakix 
すみません，チェック漏れでした…
