### ISSUE TITLE
minimal-ui 利用の検討

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#145]
@ayakix @ieiri0104 
```
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
```
に``minimal-ui``を加えると良さそう？

僕の手元にiPhoneがないので，確認してみて，良さそうだったら導入願います．

**Comment by ayakix** [comment]
@yuu-nkjm iOS8より廃止された模様です。

https://developer.apple.com/library/content/releasenotes/General/RN-iOSSDK-8.0/
