### ISSUE TITLE
チェックポイントでのチェックインタスクとタスクの整理

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#15]
* チェックポイントでのチェックインタスクは1個 (チェックインタスクが0個以上，タスクが1個以上となっていると思います)
* チェックポイントでのタスクは0個以上(現在はtaskになっているがtasksにする)
* チェックインタスクとタスクは全ての種類のタスク(Photo，QR，Selection，Descriptionなど)を全て扱える
* チェックインタスクとその他のタスクはの違いは，1) チェックインタスクはチェックポイントに必ず一つだけ存在する，2) チェックインタスクを終えてからでないとタスクを実行できない という点のみである．

現状では，checkin-*.jsとtask-*.jsで2系統ありますが，できるだけ統一して欲しいです．

**Comment by ayakix** [comment]
チェックインは1個、タスクは0個以上。
チェックインからタスクは固定

**Comment by ayakix** [comment]
チェックイン時にもaddActivityする
