### ISSUE TITLE
クイズタスク完了後に正解か不正解か表示したい

### ISSUE THREAD

**Issue by ieiri0104** [MAGCruise/magcruise-citywalk#150]
クイズタスクを完了した際に
正解ならば・・・「正解です！○ポイント獲得！」
不正解ならば・・・「不正解です！正解は○○です！」
の様なコメントを表示させたいです。

**Comment by yuu-nkjm** [comment]
クイズタスク完了後のポップアップで表示するという意味ですね？
チェックイン後はどうしますか？

**Comment by ieiri0104** [comment]
はい。
チェックイン後とは、チェックイン済みポイント一覧画面でしょうか？
チェックイン済みポイント一覧画面では、獲得ポイントによって正解か不正解かわかるので、特に正解か不正解かを文字にして表す必要はないと思います。

**Comment by reikohishiyama** [comment]
@ieiri0104 「チェックイン済みポイント」という画面が、そもそも、ないのでは？

整理すると、今、オレンジ色の右上の「メニュー」ボタンから、ドロップダウンして見られる画面は、以下のとおりのみです。

ニックネーム
---
未訪問チェックポイント
訪問済みチェックポイント
ランキング／獲得ポイント
---
使い方
はじめに
---
早稲田祭について
クレジット

画面は、以上ですね。

で、今の画面の遷移は、以下のとおり。

ナビ画面（あと～m　と出ている画面状態）で、チェックイン箇所に接近し、画面右上のオレンジ色の「チェックイン」ボタンを押す
↓
チェックインのためのタスクが出力される（＝合言葉（半角数字4桁）入力が求められる）
↓
合言葉を入力し、「回答する」ボタンを押す
↓
（間違っていた場合、「合言葉が間違っています」と出力される→「閉じる」ボタンを押す）
（合っていた場合、「チェックインに成功しました！」の文字と共に、中央画面にクイズタスクが同時に表示され、クイズ画面に遷移する）
↓
・・・
です。

@yuu-nkjm が確認されたいことは、この

合言葉を入力し、「回答する」ボタンを押す
↓
（合っていた場合、「チェックインに成功しました！」の文字と共に、中央画面にクイズタスクが同時に表示され、クイズ画面に遷移する）

という画面遷移で、同様に、
正解ならば・・・「正解です！○ポイント獲得！」
不正解ならば・・・「不正解です！正解は○○です！」
の様なコメントを表示させたい、かどうか、という質問です。

**Comment by reikohishiyama** [comment]
で、菱山の意見は、以下のとおり。

合言葉を入力し、「回答する」ボタンを押す
↓
（合っていた場合、「チェックインに成功しました！」の文字と共に、中央画面にクイズタスクが同時に表示され、クイズ画面に遷移する）

の画面遷移については、現状のままで変更なし。でよいと考えます。

整理すると、この画面では「その場に行かなければわからない合言葉（4ケタの数字）の入力」が求められます。逆に言えば、この数字は「現場で見た数字をそのまま転記入力する」だけなので、間違えるはずがないから、基本的には、（何度か入力ミスをすることはあっても）正解は目の前にあるのだから不正解入力はあり得ない、と考えてよいでしょう。
従って、

正解が入力されない限り、「合言葉が間違っています」と出力される→「閉じる」ボタンを押す、
の画面遷移を繰り返すことでよいのでは？

例えば、ですが、
合言葉に不正解→「不正解でした！正解は9999です。」→クイズタスクに進み、クイズに解答して2点獲得、といった遷移を想定すると、それは、チェックポイントに行っていないのにクイズだけ回答している状態、に相当するため、逆にまずいだろうと思います。

**Comment by reikohishiyama** [comment]
クイズタスクの方ですが、

現在は、例えば、
「伏見の大手酒造メーカを１つ挙げてください」というクイズが出て、
「月桂冠」と入力し
「回答する」ボタンを押すと
「タスクを完了しました！　（OKボタン）」
というポップアップ画面が出ます。

@ieiri0104 の提案は、この画面の記載を、
正解ならば・・・「正解です！○ポイント獲得！」
不正解ならば・・・「不正解です！正解は○○です！」
と変更したい、というものと思います。

これは、技術的に可能であり、開発者の負荷が大きくなければ、変更はよい案と思います。

不正解ならば・・・「残念！不正解です。正解は○○です。」
ぐらいの表現のほうが、いい気がします。

**Comment by reikohishiyama** [comment]
その他に、ポイントに関する表示がみられるのは、以下の画面ですよね。

「未訪問チェックポイント」画面の
　○各チェックポイント名の下に記載された、labelの冒頭
　　例．美研展覧会
　　　　（4点）最大規模の美術展覧会

「訪問済チェックポイント」画面の
　○各チェックポイントに関する表示エリアの右角にある、オレンジ色の表示
　　例．獲得ポイント　4/4
　○各チェックポイントの「label」の情報を表示する部分

これは、そのまま（変更なしで）よいでしょう。
この画面をみれば、過去の獲得ポイントや正解の振り返りができます。「あのクイズの正解は何だっけな？」「どれぐらい正解してきたのかな？」など、確認ができる点で、意味があります。
labelは、jsonからそのまま取得した値を出しているので、実害はないし、問題なし、です。
いかがでしょうか。

**Comment by yuu-nkjm** [comment]
@reikohishiyama  先生，整理して下さってありがとうございます．
以下の通り，修正しました．

- チェックイン後
![](https://i.gyazo.com/6f55621d6abe18904c43c2ce31fda499.png)

- タスク不正解
![](https://i.gyazo.com/d484531dce6870120b40af8109cb46b1.png)

- タスク正解
![](https://i.gyazo.com/3b54cb2b9eb3456b055624f79745757a.png)

#153 がmergeされたらclose．

**Comment by yuu-nkjm** [comment]
#153 がmergeされたらclose．

**Comment by reikohishiyama** [comment]
ちょっと追加的に、気が付いたのですが。。。

*********
「訪問済チェックポイント」画面
　○各チェックポイントに関する表示エリアの右角にある、オレンジ色の表示　で
　　例．獲得ポイント　4/4

の表示があります。

この4点の内訳は、チェックインで2点、クイズ正解で2点だと思いますが、
何も情報がないと、これがユーザに理解されないかもしれません。
（あれ？クイズで正解して獲得したのは2点だけど、「訪問済チェックポイント」画面では4点獲得したことになってる！なんで？？....と思う参加者が出そうな気がする）

そこで、

*********
合言葉を入力し、「回答する」ボタンを押す
↓
（合っていた場合、「チェックインに成功しました！」の文字と共に、中央画面にクイズタスクが同時に表示され、クイズ画面に遷移する）

の画面遷移の時の、「チェックインに成功しました！」の表現を

「チェックインに成功しました！（ ｘ点 獲得） 」

の表示に変更することは可能でしょうか？
（点数だけ、Web上に追加表示する。ポップアップ画面出す必要なし、で。）

（そういう意味では、ここ「変更なし」じゃなくなっちゃいますね、すいません！）

御検討お願いします。

**Comment by yuu-nkjm** [comment]
@reikohishiyama 
> 「チェックインに成功しました！（ ｘ点 獲得） 」

コメントありがとうございます．https://github.com/MAGCruise/magcruise-citywalk/issues/150#issuecomment-254675350 にあるように，もうそうなっています！

**Comment by reikohishiyama** [comment]
ありがとうございます！
（よく見てなくてすいませんー）
