### ISSUE TITLE
GPSをオンにする，位置情報サービス利用許可に関する説明

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#151]
位置情報の取得に関して、以下の事前準備を「はじめに」画面へ追加記載する。

- iPhoneの「設定」＞「プライバシー」＞「位置情報サービス」にある、「位置情報サービス」をオンにする

- iPhoneの「設定」＞「プライバシー」＞「位置情報サービス」にある、「Safariのサイト」を選択し、位置情報を「許可しない」から「このAppの使用中のみ許可」に変更する

**Comment by reikohishiyama** [comment]
Q and A 画面を作って、追加する？

**Comment by yuu-nkjm** [comment]
@ieiri0104 
位置情報サービスのオン／オフを切り替える
https://support.apple.com/ja-jp/HT203033

を参考に画像入りで説明文を作成して下さい．

画像サイズはPCで見たときに見やすくしておいて貰えたら，
あとはこちらでやります．

**Comment by yuu-nkjm** [comment]
「GPSを利用状態にする」と「サイトへの許可」の二つが必要ですね．Chromeの場合，urlバーの横を押した方が簡単と思います．

![](https://i.gyazo.com/e1658b106df971c5fd970626e12eb1a7.png)

**Comment by yuu-nkjm** [comment]
@ieiri0104 
僕の方で help.html を作りました． safariの設定のスクリーンショットをお願いします．

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生
ありがとうございます。

![img_1110](https://cloud.githubusercontent.com/assets/18714543/19582391/f0904a5a-976e-11e6-88c7-994ef2c3a6a9.PNG)
設定＞プライバシー
![img_1111](https://cloud.githubusercontent.com/assets/18714543/19582388/efb8361a-976e-11e6-9feb-a3b51b151a5e.PNG)
設定＞プライバシー＞位置情報サービス
![img_1112](https://cloud.githubusercontent.com/assets/18714543/19582389/efb91332-976e-11e6-986c-a001cc973b57.PNG)
設定＞プライバシー＞位置情報サービス＞Safariのサイト

です。
よろしくお願いいたします。
