### ISSUE TITLE
visibleTimeの期間中にピンが表示されない

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#158]
@ieiri0104  @ayakix 
コードを確認しましたが，特殊な遷移をしない限り「visibleTimeの期間中にピンが表示されない」は，
起こらないように思います． @ieiri0104 の方で，どうやれば再現するかを確認して下さい．

;; 画面の更新がされるときに updateViewsが呼ばれているので，このissueのようなことは
;; そうそう起きないように思います．

よろしくお願いします．

**Comment by yuu-nkjm** [comment]
@ayakix さん， ざっと見直しをお願いします．
@ieiri0104  から詳細な報告がありましたら，修正をお願いします．

**Comment by ayakix** [comment]
@yuu-nkjm @ieiri0104 updateViewsおよび、現在visibleTimeであり、未訪問済みのチェックポイントリストを返す、util.getNonVisitedCheckPointsは画面更新毎に呼ばれます。

ちょっと怪しいのが、OSのタイムゾーン設定です。JSで時刻や時差の取り扱い方は結構難しいです。
もしくは、OSの言語設定によりタイムゾーンがJST以外になるかもしれません。

**Comment by yuu-nkjm** [comment]
@ayakix 
ありがとうございます．しかし，日本で日本人が使っている端末で，
OSのタイムゾーンが日本以外になっているというのも考えづらいですよね．
@ieiri0104 の詳細報告を待ってから対応しましょう．

**Comment by ayakix** [comment]
@yuu-nkjm 
> OSのタイムゾーンが日本以外になっているというのも考えづらいですよね．

そうですねー確率的には低いとは思いますが、何とも言えないところですね。

@ieiri0104 こちらですが、ある特定の時間帯において、
* 全員の端末で、100%起こった
* 全員の端末で、起こったり起こらなかったり
* 特定のどなたかの端末で、100%起こった
* 特定のどなたかの端末で、起こったり起こらなかったり

だとどれでしょうか？

**Comment by ieiri0104** [comment]
@yuu-nkjm @ayakix 
連絡遅くなってしまい、申し訳ありません。
特定の端末（iphpne７）でこの状況が起こったり起こらなかったりしました。

**Comment by ayakix** [comment]
@ieiri0104 ご情報ありがとうございます。なるほどー。一番ややこいやつですね :(
少なくともタイムゾーンではなさそうですね。

**Comment by yuu-nkjm** [comment]
@ayakix 
2回目実験でOKだったのでひとまずOKで．
たしか1回目実験では「チェックポイント画面で選択する度にリロードしない」版
だったと思うので，そのせいだったのでしょう．

**Comment by ayakix** [comment]
@yuu-nkjm こちら承知しました。
