### ISSUE TITLE
「よくある質問」について

### ISSUE THREAD

**Issue by ieiri0104** [MAGCruise/magcruise-citywalk#161]
10月18日の結果をもとに、よくある質問をまとめます。

Q. 建物に入ったときに、距離情報やコンパス情報がおかしくなる
A. 建物内ではうまくGPSを使えず、ナビ画面がおかしくなる時がある

Q. チェックインタスクに正しい4つの数字を入れているのに、チェックインできない
A. 半角英数字で入力してください

アンサーの部分は、当日僕が対応した返答です。間違っていたら、訂正お願いいたします。
量があるわけでもないので、中島先生、菱山先生のおっしゃる通り、新しいページを新たに作る必要もないように思います。
よろしくお願いいたします。

**Comment by yuu-nkjm** [comment]
@ieiri0104 

> Q. チェックインタスクに正しい4つの数字を入れているのに、チェックインできない
> A. 半角英数字で入力してください

これが発生した端末を教えて貰えますか？``type="number"``を指定しているので，
半角数字以外は入らないようになっているはずです．Chromeでは発生しませんでした．

**Comment by ieiri0104** [comment]
safari ios　でこの現象が出ました。
機種はiphone6でした。

**Comment by yuu-nkjm** [comment]
@ieiri0104 

了解です． iOSのnumberの処理がおかしいようですね．
#169 で対応しました．空白や全角数字を扱える用にしました．

> 「A. 半角英数字で入力してください」
入力欄にここまで表示しているにも関わらずこの質問が出るということなので，
このQ&Aを作ったところで，無駄に終わりそうですね．

![](https://i.gyazo.com/a660c5eab6a635743a89bcd4328bde3a.png)
