### ISSUE TITLE
バッジ仕様検討

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#17]
何かの課題が設定されており，それをクリアすることで，バッジ（アイコン画像）を獲得できる機能，経験値によってレベルアップして獲得できるバッジなどが想定されます．

たとえば，お菓子屋さんを3つ回ったら，スイーツバッジ獲得，とか，
各所でクイズに解答し，累積で正解が2個溜まったら，「初級者バッジ」
累積で正解が5個溜まったら，「中級者バッジ」
累積で正解が10個溜まったら，「上級者バッジ」
みたいなもの．

https://github.com/nkjmlab/MAGCruiseCityWalk/issues/6

**Comment by reikohishiyama** [comment]
間違えてタイトル変えちゃいました、↑のは削除しておいてください！

**Comment by reikohishiyama** [comment]
(バリエーション)
単に解答を登録すれば、バッジ付与
正解を３つで、バッジ付与
訪問１０箇所（どこでもよい）で、バッジ付与
カフェ３箇所（カフェに限定）で、バッジ付与
１０時から１２時までにチェックインでバッジ付与
写真をつけてしょうきさんを報告すると、バッジ付与
しょうきさんを5つ見つけて報告すると「5つ発見した」（1つ見つけた時とは異なる）バッジ付与
