### ISSUE TITLE
移動ログ (タスクに関係しないログ)

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#19]
タスクに関係したログはaddActivityの時に取れる．それ以外のログをどうするか．

https://github.com/nkjmlab/MAGCruiseCityWalk/issues/5

**Comment by ayakix** [comment]
現状、下記情報を取得＆送信しています。
クライアントでは、内部に送信待ちキューを用意し、位置情報が更新される度に、移動ログをエンキューします。
別スレッドで、10秒に1回送信待ちキューを監視し、データがある場合は、送信し、データを削除しています。JsonRPCによるエラーハンドリングの方法がわからないため、送信エラー時にもキューに溜まっているムーブメントデータをフラッシュしてしまっています。（本来ならば、送信エラー時には、ムーブメント配列に再度エンキューしたい。）

https://github.com/MAGCruise/magcruise-citywalk/pull/37/commits/edcc4babc4e74e03a7126d84dd89e42ed16be79a#diff-caa4842b2b643f9a68ac54ff99a2d5e7R221

```
userId				: getUserId(),
lat     			: pos.coords.latitude,
lng    	 			: pos.coords.longitude,
heading 			: cHeading,
checkpointGroupId	: getCheckpointGroupId(),
checkpointId		: checkpointId,
```

**Comment by yuu-nkjm** [comment]
;; 書いている途中で消してしまった…．

https://github.com/MAGCruise/magcruise-citywalk/commit/19bc453583e2751b3a66d62a6cd3126f317c6990#diff-0b28d9dfbaff51270b6a5be64ddcf9e3R2

``var JsonRpcRequest = function(url, method, params, done, fail)```の第5引数に呼び出しがfailしたときのコールバックを書けます．

呼び出しは成功したけど，サーバ側でヌルポが発生したような場合は，data.errorにエラーが入っています．
![](https://i.gyazo.com/0d5d84d2b7772ef0e1f9e60358810bbf.png)

**Comment by ayakix** [comment]
@yuu-nkjm お、なるほど。ありがとうございます。

**Comment by ayakix** [comment]
https://github.com/MAGCruise/magcruise-citywalk/pull/39/files

修正しました。ネットワーク切断時に、移動ログをローカルに再度格納することを確認しました。
