### ISSUE TITLE
addActivityをネットワーク接続出来ないときでもできるようにする

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#201]

**Comment by ayakix** [comment]
@yuu-nkjm こちら承知しました。ミーティングであったように、今回の早稲田祭が終わり次第取り組みます。

**Comment by yuu-nkjm** [comment]
@ayakix 
画面遷移後もaddActivityをすることを覚えておかないといけないので，util.jsあたりに仕込むのがいいですかね．

**Comment by yuu-nkjm** [comment]
#219 で完了のはず．
