### ISSUE TITLE
誤差の円表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#208]
@ayakix 

- 同じ場所に居続けるとどんどん円が濃くなってしまう？ (どれだけ円を残しておくかなど)
- 縮尺によって円のサイズが変わりすぎる (当たり前だけど，zoomが小さきときは小さすぎ，zoomが大きいときは大きすぎになりやすい)

どのスケールでも「半径10pxの円が一つだけ」にすることは簡単ですか？
現状だと，誤差がある場所に長く止まると，画面が真っ青になります．
できるだけ安全サイドに倒したいです．

**Comment by ayakix** [comment]
> 同じ場所に居続けるとどんどん円が濃くなってしまう？ (どれだけ円を残しておくかなど)
失礼しました。再描画毎に前の円は削除するようにします。

> 縮尺によって円のサイズが変わりすぎる
こちら調べたんですが、出てきませんでした。時間がある時にもう一度調べてみますね。

また、ちょっとダサいですが、`このズームレベルの時は、この半径の円を描画する`という法則を全てのズームレベルで持っておけば、見た目上はある程度揃えられそうですね。

**Comment by yuu-nkjm** [comment]
#209 で解決！
