### ISSUE TITLE
初期化データのJSON差し替え機能

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#213]
初期化データを一度読み込んだら，もう読み込まれない．修正データを読み込ませたいときの機能が必要．
オフライン対応とのトレードオフ

**Comment by reikohishiyama** [comment]
今回、11/5の時点でワセナビ受付ブースを3箇所設定していましたが、現場の判断で、11/5終了時点で翌日（11/6）はこれを1箇所へ統合することになりました。
このため、この変更を11/5夜にかけたところ、その情報が「変更以前にログインした参加者のチェックインポイント一覧には反映されない」ということになりました。
（変更後に初ログインの人には、反映される）

実際には、１～２か月ないしそれ以上（半期、１年）といった長期で連続利用することが想定されるので、以前からの利用者のデータは初めて利用したときのまま、というのではなく、変更されるようにしたいですー。

**Comment by yuu-nkjm** [comment]
@reikohishiyama @ayakix 
もともとは「1日～2日ものイベント」という想定だったので，長期運用だと色々と考えることが出てきそうです．

JSONの差し替えは早稲田祭のような短期ものでも必要になることがあると思います．

しかし，実現は簡単なのですが，運用がかなり難しくなります．

例えば，データを分析するときに「全チェックポイントID集合」というものを考える時に，
チェックポイントがあったり，なかったりすると困ります．

また，同一クイズで満点が変わったりするとややこしいです．

例えば，ユーザAは満点が最初に4ptで正解して4ptもらったとします．
その後で，満点を8ptにしたとします．

そうすると，ユーザAの表示は4pt/4ptを維持しなくてはなりませんが，
それには今の満点は8ptで，昔の満点は4ptであったということを記憶し，
それを正しく処理しなくてはなりません．

クイズの正解が間違えていたから変更するなども，正解が誤答になる，
誤答が正解になる，また，それらの表示などを含めると，ややこしくなります．

- 表示時間帯を変えられる
- ラベル名は変えられる

など，変更して良い事項を決めておく必要があります．

**Comment by yuu-nkjm** [comment]
@reikohishiyama 
運用方法の検討は継続課題として，差し替え機能は実装しました！
