### ISSUE TITLE
あったらいいなと思った機能（ご参考）

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#217]
【ご参考】
あったらいいな、と思った機能の備忘録。

ある場所にチェックインし、クイズに解答後、その次に行こうとする場所として、
（カテゴリにかかわらず）現在地から最も近い順にチェックポイントを表示してくれる機能。

似たような場所（ルート）を回っている人の情報にもとづいて、
「ここに来たひとは、ついでに、ココにも寄っています！」的なプッシュ。

**Comment by yuu-nkjm** [comment]
@reikohishiyama 
コメントをありがとうございます．
本当に必要になったら， #220 , #221 にコメントくださいー．
