### ISSUE TITLE
距離順のチェックポイント表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#221]
> ある場所にチェックインし、クイズに解答後、その次に行こうとする場所として、（カテゴリにかかわらず）現在地から最も近い順にチェックポイントを表示してくれる機能。

#217 #220 とまとめると，「カテゴリ」だけでなく「距離順」「類似度順」のようなチェックポイント一覧が欲しいということ．リストにソート機能を持たせるようなことも考えられるが，リストをタブ化するのが良さそう．ちょっと画面がせまいかなー

**Comment by yuu-nkjm** [comment]
@reikohishiyama 

距離順表示(カテゴリなし)，カテゴリ表示，サブカテゴリ表示に対応しました！
![](https://i.gyazo.com/b4c1f7fab2cadb316710dd1364e374d9.png)

**Comment by reikohishiyama** [comment]
なんと！ありがとうございます！
実際には、

ある場所で、チェックインする
↓
近辺をウロウロして、ついでに近いとこのポイントがあったら、チェックインしとこう、

とか、

ある場所でチェックインする
↓
近辺をウロウロしてたら、たまたまチェックインポイントをみつけた
↓
そのチェックインポイントが、どのカテゴリにあるか分からないから探せないが、チェックインしたい

といったニーズに対応出来ます^_^

ありがとうございます！

**Comment by yuu-nkjm** [comment]
@reikohishiyama 

なるほど！ナビという観点でなく，当初のオリエンテーリングという観点からは，現在地付近の情報が分かると嬉しいことが色々とありそうですね．

**Comment by reikohishiyama** [comment]
@yuu-nkjm 

そういう意味では、「ここ来た人は、ここにも行ってます」も、これに近い意図があります。

ある場所で、チェックインする
↓
ここに来た人が次に行っている場所って、この近辺にあるのかな？
↓
どこだろ？

（ただ単に、近い順じゃなくて、人気あるような場所が他に近くにあるんじゃないかとか、絵が好きな人が行く場所って他に近くにないかな、とか、そういった、ある種の意図をもった人の思考様式に沿ったもの）

とか

ある場所（例えば、受験生サポートサークルのイベント）にチェックインする
↓
ここに来た受験生って、ほかにどっかいってるのかな？
↓
そこに、あたしもいってみたい。

こういうニーズに対応できそうなので、メモしましたー。
