### ISSUE TITLE
京都データの更新

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#23]
@ieiri0104
dropboxにある京都データですが，足りない項目があるので追加して下さい．

チェックポイントのname属性，label属性を入れてください．

nameには「本能寺」のような施設名，labelには施設名の短い説明を書いて下さい．
またタスクのid属性を入れてください．
これはタスク内でユニークであればよいです．
現在，1チェックポイント1タスクになっているとしたら，checkpoint_id-qr，checkpoint_id-selection
のようにすればよいと思います．
magcruise-citywalk-server\src\main\webapp\json\checkpoints-and-tasks の下に入れて，随時，更新してください．

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生
京都データの更新を行いました。
位置情報も携帯写真のGPSでは不正確と前回分かったので、GoogleMapのデータに変えております。

よろしくお願いいたします。

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生
あわせて、早稲田理工バージョンの位置情報の変更と、足りない項目の補充を行いました。

よろしくお願いいたします。

**Comment by yuu-nkjm** [comment]
@ieiri0104 

> またタスクのid属性を入れてください．
> これはタスク内でユニークであればよいです．
> 現在，1チェックポイント1タスクになっているとしたら，checkpoint_id-qr，checkpoint_id-selection

checkpoint_id-qr をそのまま書いたら，ユニークにならないですよね．
cafeteria-qr，pc-room-qrということです．

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生

すいません。ありがとうございます。
訂正し、サーバを起動しようとしたところ、次のようなエラーが出てしまいました。

![image](https://cloud.githubusercontent.com/assets/18714543/18307711/8c26033e-752c-11e6-9c14-2c2c8d6795d8.png)

/magcruise-citywalk/src/main/java/org/magcruise/citywalk/websocketに問題があるみたいです。

**Comment by ieiri0104** [comment]
@yuu-nkjm 先生

エラーの理由の意味などを調べて、今どのように改善するか考えてみたのですが、何が間違えているのかよくわからなかったため、連絡させていただきました。
よろしくお願いいたします。

**Comment by ayakix** [comment]
@yuu-nkjm こちら私も同じ状況になります。
masterブランチで、MavenのForce update後です。

**Comment by yuu-nkjm** [comment]
@ieiri0104 @ayakix 

Mavenは関係なくて，コミット漏れしてました．
すみません…

**Comment by ayakix** [comment]
@yuu-nkjm ありがとうございます。エラーはなくなったのですが、サーバを起動すると404が出てしまいます。パス等は変わっていないですよね？

@ieiri0104 現状、いかがでしょうか？

**Comment by yuu-nkjm** [comment]
@ieiri0104 @ayakix 
大分前に変えましたが，http://localhost:8080/magcruise-citywalk/  です．
それでアクセスできなければ，他のエラーが出てると思います．

**Comment by ieiri0104** [comment]
@yuu-nkjm @ayakix 
ありがとうございます。
新しく京都バージョンを追加する前は、サーバを起動してもエラーが出ないのですが、京都バージョンのjsonを追加してサーバを起動してみると、404が出てしまうという状況になりました。
eclipseではエラーは出ておりませんでした。

**Comment by ayakix** [comment]
404の件ですが、下記っぽいですね。
http://localhost:8080/magcruise-citywalk-server/app/index.html

**Comment by ayakix** [comment]
<img width="761" alt="2016-09-07 21 04 19" src="https://cloud.githubusercontent.com/assets/907388/18311341/b2ec29f0-753e-11e6-8403-25bdd550fe9e.png">

**Comment by yuu-nkjm** [comment]
@ayakix 

http://localhost:8080/magcruise-citywalk/
が正しいです．

一時期，http://localhost:8080/magcruise-citywalk-server/ だったので，
それが残ってますが実行には問題ありません．

**Comment by yuu-nkjm** [comment]
@ieiri0104 

京都バージョンのjsonを追加するとおかしいということであれば，京都バージョンのjsonがおかしいということですね．

**Comment by ayakix** [comment]
@ieiri0104 Eclipse管理のworkspaceに、ServersというTomcatの設定ファイルがあります。その中にあるserver.xmlの下記行、pathの`-server`を消せば動きます。もしくはServerをEclipse上で一度消しても動くかもしれません。
(JSONの件は別問題だと思いますが、404はこれで解決できるかも)

```xml
<Context docBase="magcruise-citywalk-server" path="/magcruise-citywalk-server" reloadable="true" source="org.eclipse.jst.jee.server:magcruise-citywalk-server"/></Host>
```

@yuu-nkjm こちらの対応でよろしいでしょうか？

**Comment by yuu-nkjm** [comment]
@ieiri0104  @ayakix
@ayakix さんのいうとおり，サーバの起動設定を作り直すか，server.xmlを修正するで良いと思います．
MavenのEclipse機能やEclipseのTomcatデプロイ機能は，ちょいちょいおかしくなります．

**Comment by ayakix** [comment]
@yuu-nkjm ご確認ありがとうございます。Slackの情報ですとGitHubのリモートリポジトリのみが変わっただけで、エンドポイントは変わってないように思っていました。
また、Git管理していない各人依存のローカルファイルに変更があった場合には、教えて頂けますと助かります。
何卒、宜しくお願い致します。

**Comment by ieiri0104** [comment]
@yuu-nkjm @ayakix 
ありがとうございます。
tomcatでのエラーは出ていないです。
![image](https://cloud.githubusercontent.com/assets/18714543/18311970/519addf0-7542-11e6-816e-1c8c9c4fe9a0.png)

コンソール画面で
クラス org.magcruise.citywalk.ApplicationContext のリスナインスタンスにコンテキスト初期化イベントを送信中の例外です
と言われているのが原因ではないかと思い、調べてみております。

**Comment by yuu-nkjm** [comment]
@ieiri0104 

そのコンソールがtomcatのコンソールなのですが…
コンパイルエラーでなく実行時エラーが出てるはずですよ，ということです．

**Comment by yuu-nkjm** [comment]
@ayakix 

> また、Git管理していない各人依存のローカルファイルに変更があった場合には、
> 教えて頂けますと助かります。何卒、宜しくお願い致します。

了解です．

**Comment by ieiri0104** [comment]
@yuu-nkjm 
すいません。勘違いしておりました。
![image](https://cloud.githubusercontent.com/assets/18714543/18313638/99794802-754a-11e6-9e1e-5f00dbbf84d0.png)

確認なのですが、京都版のjsonを加えて動かす際、magcruise-citywalk-server\src\main\webapp\json\checkpoints-and-tasksの下にjsonを加える事以外にやることは何かありますか？

**Comment by yuu-nkjm** [comment]
@ayakix @ieiri0104 

デプロイパスに依存している箇所はないので，http://localhost:8080/magcruise-citywalk/  でも
http://localhost:8080/magcruise-citywalk-server/ でも，動く方で問題ないと思います．

@ayakix が404になるといっていたのは，もう一階層下で，アプリケーションパスを
deploy-path/views/ から deploy-path/app/ に変えたせいだと思います．

deploy-path/index.html からのアプリケーションへのリンクを修正したので，
この変更に関して，特に言わなくてもいいかと思ってしまいました．すみません．

**Comment by yuu-nkjm** [comment]
@ieiri0104 
Eclipse なのか tomcatなのか良く分かりませんが，変な状態が残ってしまっていそうですね．

windowsの再起動 → サーバビューで「クリーン」 もしくは サーバ設定の再生成 → 起動

としてみたら良いと思います． Eclipseから起動したtomcatがゾンビになったり，Eclipseから
Tomcatのワーキングディレクトリをクリーンできなかったりすることがあるようです．

>確認なのですが、京都版のjsonを加えて動かす際、magcruise-citywalk-server\src\main\webapp\json\checkpoints-and-tasksの下にjsonを加える事以外にやることは何かありますか？

基本的には，ないです．エクスプローラを使ってJSONをおいた場合は，Eclipseが認識しないので，
プロジェクト上で「更新」をする必要はあります．Eclipse上で当該JSONファイルを開くことができればOKです．

**Comment by ayakix** [comment]
@yuu-nkjm あ、なるほど！そういうことなんですね。承知しました。

**Comment by ieiri0104** [comment]
@yuu-nkjm 
ありがとうございます。
windowsの再起動から進めたら、そのエラーはなくなりました。

![image](https://cloud.githubusercontent.com/assets/18714543/18340291/1725d47a-75df-11e6-9845-4f33584b8ae9.png)

しかし、次にこういうエラーが出てしまいました。
org.magcruise.citywalk.ApplicationContextのクラスが見つからないという事でしょうか？

**Comment by yuu-nkjm** [comment]
@ieiri0104 
えっと，エラーはかわってないですね．プロジェクトを削除して最初からやり直した方がよいと思います．

**Comment by ieiri0104** [comment]
@yuu-nkjm 
エラーは同じことを知りませんでした。すいませんでした。ご指摘ありがとうございます。

プロジェクトを削除して、windowsを再起動させて、最初からやり直して起動させてみたのですが、やはり同じエラーが出てしまいます。

京都版を加える前はうまくいったことを考えて、早稲田版との違いを考えたのですが、json自体は両方validでした。違いはmagcruise-citywalk-server\src\main\webapp\json\initial-dataの下にjsonが入っているかどうかだけな気がするのですが、これは関係ないでしょうか？

**Comment by yuu-nkjm** [comment]
@ieiri0104 

> 京都版を加える前はうまくいった

今でもkyoto.jsonを取り除くと正しく動く(早稲田版の画面が正しく動く)のですか？

JSONがvalidというのはどういう意味でしょうか？JSONがJSONとしてvalidというだけでは意味がありません．例えば，{"hoge":1}と書いたらJSONとしてはvalidですが，インポートするとエラーになります．

initial-dataのディレクトリ以下のJSONは必要になったときにロードされるので，起動時には関係ありません．

**Comment by ieiri0104** [comment]
@yuu-nkjm 
なるほど。ありがとうございます。
今でも京都版を取り除いたら動きます。ですので、やはり京都版のjsonに問題があるのでしょうか？
形式としては、早稲田版と同じになっております。

**Comment by yuu-nkjm** [comment]
@ieiri0104 

> 今でも京都版を取り除いたら動きます。ですので、やはり京都版のjsonに問題があるのでしょうか？

きっとそうでしょうね．

slackの方でも送りましたが，slackでjsonデータを送ってくれますか？
GitHubでもslackでも，自分宛にメッセージが来たら，すぐ分かる様に設定しておいて下さい．

**Comment by ieiri0104** [comment]
@yuu-nkjm 
申し訳ありませんでした。
了解です。
早速slackで送らせていただきます。

よろしくお願いいたします。

**Comment by yuu-nkjm** [comment]
@ieiri0104 

* チェックポイント一覧でのアイコンの収集
* answerQrに値を設定

**Comment by yuu-nkjm** [comment]
@ieiri0104 ↑の残り作業が終わっていたら，closeして下さい．
