### ISSUE TITLE
バッジ取得情報，ランキング情報を取得するJSON-RPCの実装

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#28]
データ形式は，Activityを投げたときに返ってくる RewardJson と同じでよい？
名前があんまり良くないが．

**Comment by ayakix** [comment]
こちら助かります。
現状は、下記のような感じですかね？

```
int rank,
List<String> badges
```

@reikohishiyama 先生が、バッジイメージを用意してくださってるので、バッジ配列がList<Map<String,String>>となるかもですね。

ex.)
```
{
  "rank": 5,
  "badges" : [
    {"name": "AED王", "img":"icon_badge_aed.png"},
    ...
  ]
}
```

あと、ランキングは、「自分が何位か？」というのを表示するとは思うのですが、１位から１０位までのランキングや全ての参加者のランキングを表示するのでしょうか？（それはまた別APIかもですが）

**Comment by yuu-nkjm** [comment]
RewardJsonは，名前としても中身としても適当でなさそうですね．ランキング画面用のRankingsJsonとバッジ画面用のBadgesJsonを定義して，それを取得するためのAPIを用意する方が良さそうですね．

Badgeも名前+imgのmapになりそうですね．ここも追々準備しておきます．

**Comment by ayakix** [comment]
@reikohishiyama @yuu-nkjm
こんな感じかな？というのをモックで作ってみました。
https://github.com/MAGCruise/magcruise-citywalk/pull/29

表示したいもの、表示する必要が無いもの等ご意見あればよろしくおねがいします
