### ISSUE TITLE
ナビ画面での地図の縮尺

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#32]
ナビ画面で地図が広域表示され過ぎている．
と思ったけど，現在地からチェックポイントまでの距離で変わるようになっている？

**Comment by ayakix** [comment]
![2016-09-12 12 35 36](https://cloud.githubusercontent.com/assets/907388/18423982/92138e44-78e5-11e6-9dae-2f764d254201.png)

@yuu-nkjm こちら修正しました。また、簡易な修正なためノーチェックでマージしました。

**Comment by yuu-nkjm** [comment]
@ayakix OKです！
