### ISSUE TITLE
ユーザIDをメールアドレスにする？

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#33]
ユーザIDにメールアドレスを使わせる？
ユーザIDにメールアドレスを使った場合，@が予約文字になっていることに注意．
他にもメールアドレスには使えるけど，URLに含められないものがないか注意する必要がある．

メールアドレスにすると他の人にアクティビティを通知するときに，ユーザ名を表示するのがマズいですね．
運用を含めて再検討が必要． > @ayakix

**Comment by ayakix** [comment]
ユーザー名を@の前の部分にするとかでしょうか。
例えば、`ayakix@gmail.com`ですとユーザー名が`ayakix`になります。

**Comment by yuu-nkjm** [comment]
ログイン時はメールアドレスを使って，アクティビティの表示には@の前の部分を使うということですね．
メールアドレスの前半は，電話番号っぽいものが入っていたり，個人情報っぽいものが入っていたり
することもあるので，表示は切り分けた方が良さそうに思います．
```
ログイン (ユーザの識別に使われます)
　ユーザ名：
```
としておいて，初回ログインであれば
```
ニックネーム登録(他の人に通知されることがあります．)
　ニックネーム ：
```
と言う画面に遷移．そうでなければチェックポイント画面に遷移で，どうでしょうか？

**Comment by ayakix** [comment]
@yuu-nkjm こちら返信遅れまして大変申し訳ありません。

> ログイン (ユーザの識別に使われます)
>　ユーザ名：

ユーザーの識別子については、現状メールアドレスでよろしいでしょうか？

1. メールアドレスを入力
2. メアドが登録済みの場合、4へ。未登録の場合3へ。
3. ニックネーム登録画面
4. チェックポイント一覧画面を表示

**Comment by ayakix** [comment]
ログインの遷移
1. login(メアド,””)
2. 返り値が`true`の場合、ニックネーム登録済みとして、4へ。
3. 返り値が`false`の場合、ニックネーム未登録→ニックネーム登録画面へ→register(メアド、ニックネーム)。4へ。
4. チェックポイント一覧画面の表示

**Comment by ayakix** [comment]
早稲田祭でメアドはやめて欲しいとのことなので、開発ペンディング。

**Comment by yuu-nkjm** [comment]
@ayakix 
ニックネーム+パスワードにしないとだめそうですね．ちょっと考えましょう．

**Comment by ayakix** [comment]
@yuu-nkjm （仕方ないのですが）今回の早稲田祭と、当初のシティウォークサービスで仕様が若干ずれてきてしまいましたね。早稲田祭が終わってから仕様変更かもしれませんね。

**Comment by yuu-nkjm** [comment]
userId, groupId, nicknameあたりを整理する必要がありそうです．wasedasaiでは，

-  userIdはユーザが入力したもの． サーバに送って登録済みならそれに適当なsuffixをつけて提案
-  groupIdは""
-  nicknameは，userIdと同一

で良さそうですかね．ユーザの識別キーをuserIdだけにするか，groupIdとuserIdの複合キーにするか，若干迷います．

**Comment by ayakix** [comment]
ユーザー情報の保存
セッションストレージ→ローカルストレージ

セッションストレージにユーザー情報がある場合、
自動的にログイン画面に飛ばして、自動的にログイン


セッションストレージにユーザー情報がない場合、
レジスター画面に飛ばす。
ユーザー名が被った場合には、レジスターできない＆ユーザー名をリコメンド。
