### ISSUE TITLE
チェックポイント一覧画面における訪問済みチェックポイントの表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#34]
@ayakix 

チェックポイント一覧画面でチェックポイントが訪問済みか訪問済みでないかが分かりません．
グレーアウトするぐらいが適当でしょうか．検討をお願いします．

**Comment by ayakix** [comment]
承知しました。考えてみます。

**Comment by ayakix** [comment]
<img width="398" alt="2016-09-25 19 37 31" src="https://cloud.githubusercontent.com/assets/907388/18814775/2b9b1290-8358-11e6-8665-ec290e377e7e.png">

右上に`訪問済み`と文字を表示してみました。
