### ISSUE TITLE
タスクに対するレスポンス

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#35]
チェックインすると「チェックインに成功しました」と出るが，タスクはバッジなどが貰えなかったとき，
何も起こらない．何らかのレスポンスを返すべき．

**Comment by ayakix** [comment]
`タスクを完了しました！` と文字を表示するように修正しました。

![2016-09-25 18 00 41](https://cloud.githubusercontent.com/assets/907388/18814075/290396dc-834a-11e6-8999-e8f14b520b98.png)
