### ISSUE TITLE
自分の位置情報について

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#51]
今日のミーティングで，地図上で自分自身の位置情報（通常，青丸で表示されているような位置情報）を，表示するかどうか，というトピックがありました．
この自分自身の位置情報ですが，ミーティング後に再度考えてみると，綾木さんのご提案どおり，「コンパスとの連動，ゲーム性を考慮し，自分の位置情報は表示しない」という設定もあり」と思いました．
（実際，オリエンテーリングでは，目的地に対する自分の位置情報が相対的に把握できないことで試合感がでています）

そこで今回，京都での実験で，この，自分の位置情報の表示効果について，比較実験できないかと思います．そのため，自分の位置情報を表示する設定と，表示しない設定を，管理者ベースで何らかのかたちで切り替えできたらうれしいのですが...これは，.技術的に可能でしょうか？

実験としては，あらかじめ，以下の2つの被験者実験群を作ります．

(1)　自分の位置情報を地図上に表示せず，訪問一覧にあるスポットをgoogleのピンで刺しておく．

(2)　自分の位置情報を地図上に表示し，訪問一覧にあるスポットと同時に，自分の位置と訪問したいスポットの位置が表示されている状態にする．

この２つの被験者実験群について，「ここへ行く」ボタンの押下に違いがあるかどうか，ナビゲーション機能の使い方がどのように変わるかを調べてみたいと思います．いかがでしょうか．

**Comment by yuu-nkjm** [comment]
@ayakix さん
ひとまずは手抜きで「現在地を常に表示する」にしておいてもらえますか？
最終的にはinitialdataの中に``drawCurrentPosition: true``のようなフラグを含めましょう．

**Comment by ayakix** [comment]
@yuu-nkjm 承知しました。

**Comment by ayakix** [comment]
![2016-09-30 20 00 31](https://cloud.githubusercontent.com/assets/907388/18989778/b4a6d7a6-8748-11e6-8181-c450d98496b1.png)
@reikohishiyama @yuu-nkjm スクリーンショットの様に円を描いています。円の半径はGPSの誤差を表しています。（固定値mにすることも可能です。）

**Comment by ayakix** [comment]
チェックポイント一覧画面において、現在地を表示するようになりました。
必要に応じて、コメントアウトすれば、チェックポイント一覧画面/ナビ画面共に、位置情報を表示しないようになっていますので、その際はコードを変更下さい。

**Comment by reikohishiyama** [comment]
コメントアウト形式で対応ということで、大変ありがたいです。ありがとうございました！
