### ISSUE TITLE
獲得ポイント表示

### ISSUE THREAD

**Issue by ayakix** [MAGCruise/magcruise-citywalk#55]
訪問済みチェックポイント一覧の各項目に獲得ポイント数を表示する。

**Comment by ayakix** [comment]
@yuu-nkjm こちら、ユーザーのチェックポイント毎の獲得ポイント数は、サーバ側から返して頂けるという認識でよろしいでしょうか？

**Comment by yuu-nkjm** [comment]
はい！どんなAPIにしましょう？こんな感じ？

```
VisitedCheckpoint[] getScores(String userId, String groupId) 

VisitedCheckpoint{
    String id;
    double score;
}
```

**Comment by yuu-nkjm** [comment]
総ポイントが見られた方が良さそうですね．ランキングページ？バッジページ？訪問済みチェックポイントページ？それらのいくつかのページ？

**Comment by ayakix** [comment]
ユーザーの獲得総ポイントは、VisitedCheckpointの配列より、scoreを足し合わせることで取得することができるので、クライアントサイドでも構いません。

各チェックポイントの最大（満点）ポイント数を教えて頂けると助かります。`2/6ポイント`のように表示する可能性があります。

**Comment by yuu-nkjm** [comment]
```
BadgeJson[] getBadges(@Parameter(sample = "ayaki") String userId);
```
あたりって，checkpoingGroupIdも引数に取らないとおかしいですね．

**Comment by yuu-nkjm** [comment]
むむむ，checkpointのスコアはtaskのスコアの総和にしないといけないのか．

**Comment by yuu-nkjm** [comment]
追加しました．

#### データ構造
```java
public class VisitedCheckpointJson {
	private String checkpointId;
	private double score = 0.0;
	private double point = 0.0;
}
```
#### メソッドシグネチャ
```java
	VisitedCheckpointJson[] getVisitedCheckpoints(
			@Parameter(sample = "sample-at-magcruise.org") String userId,
			@Parameter(sample = "waseda") String checkpointGroupId);
```
#### 呼び出し結果の画面
![](https://i.gyazo.com/6d6c474839372f8050383396381d8024.png)

**Comment by ayakix** [comment]
![2016-09-30 19 54 24](https://cloud.githubusercontent.com/assets/907388/18989608/d8777de4-8747-11e6-9ca1-33674bc584c6.png)

@yuu-nkjm ありがとうございます。現状、スクリーンショットのように表示しています。
