### ISSUE TITLE
チェックポイント一覧画面のマップピンの色を動的に変更できるようにする

### ISSUE THREAD

**Issue by ayakix** [MAGCruise/magcruise-citywalk#56]
ex.) 「black」「brown」「green」「purple」「yellow」「blue」「gray」「orange」「red」「white」

参考：http://www.ajaxtower.jp/googlestaticmaps/marker/index4.html

**Comment by ayakix** [comment]
@reikohishiyama 色変更可能みたいです。
![2016-09-27 0 26 43](https://cloud.githubusercontent.com/assets/907388/18840319/267108dc-8449-11e6-98c5-4a7deb95b00a.png)

利用可能な色は、red, blue, green, purple, yellow, orangeです。
Googleが画像データを用意してくれているみたいです。

http://maps.google.com/mapfiles/ms/icons/red-dot.png
http://maps.google.com/mapfiles/ms/icons/blue-dot.png
http://maps.google.com/mapfiles/ms/icons/green-dot.png
http://maps.google.com/mapfiles/ms/icons/purple-dot.png
http://maps.google.com/mapfiles/ms/icons/yellow-dot.png
http://maps.google.com/mapfiles/ms/icons/orange-dot.png

@yuu-nkjm 各チェックポイントのパラメタとして、色値を返して下さい。
ex.)

```json
{
	"checkpoints": [{
		"id": "cafeteria",
		"label": "お昼は激こみ",
		"lat": 35.706489,
		"lon": 139.708019,
		"name": "大食堂",
		"markerColor": "red",
		}
		...

```

**Comment by reikohishiyama** [comment]
追加でお調べ頂いて、ありがとうございます！
今週水曜（9/28）PMに、家入氏と対面ミーティングするので、その際にどのように色分けを使うかを検討します。
