### ISSUE TITLE
ThymeleafModelクラスのインポート

### ISSUE THREAD

**Issue by ayakix** [MAGCruise/magcruise-citywalk#67]
https://github.com/MAGCruise/magcruise-citywalk/commit/a30eb91a1d2705982b56346746545ac332b5be9a
で追加した `org.nkjmlab.webui.common.jaxrs.ThymeleafModel` が解決できません。

Maven Updateもしましたが、インポートエラーが出てしまいます。ご確認頂けますでしょうか。

**Comment by yuu-nkjm** [comment]
@ayakix さん，maven repoへのデプロイを忘れていました．
いまdeployしましたので，もう一度Maven Updateして下さい！

**Comment by ayakix** [comment]
ありがとうございます！アップデート後、動作を確認しましたー。
