### ISSUE TITLE
描画時間帯機能

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#70]
早稲田祭で使いたいということなので．

**Comment by reikohishiyama** [comment]
@ieiri0104 @yuu-nkjm 想定されるのは，以下のような仕様でしょうか．間違ってたら修正ください．

描画時間帯＝地図上に当該チェックポイントを表示する．
非表示時間帯＝地図上に当該チェックポイントを表示しない．
 
更に，
物理的には同じ場所でも，時間帯が違う場合はそれぞれ違うチェックポイントとして記述する．
描画時間帯，非表示時間帯は，チェックポイントごとに指定する．

想定される設定ケース事例：
大隈重信像前で，午前中に連続して２つのパフォーマンスが行われ，それぞれにチェックイン機能を提供する場合．

チェックポイント：大隈重信像前－企画その1
内容：チアリーディング部のパフォーマンス
内容の開催日時：午前10時～11時
描画時間帯：午前9時45分～午前10時半
非表示時間帯：描画時間帯以外の全時間帯

チェックポイント：大隈重信像前－企画その2
内容：ゲタッパーのパフォーマンス
内容の開催日時：午前11時～12時
描画時間帯：午前10時45分～午前11時半
非表示時間帯：描画時間帯以外の全時間帯

**Comment by reikohishiyama** [comment]
説明補足：「ゲタッパー」：下駄を履いて踊る早稲田大学のサークル．所属メンバー数は，約80名．

**Comment by reikohishiyama** [comment]
「描画（表示）」「非表示」について，時間制御の対象としては，
- [ ] 地図上へのチェックポイント候補の表示
- [ ] チェックポイント候補一覧への表示
- [ ] クイズの表示
- [ ] チェックイン済一覧への表示
がありそう．

想定される状況を以下にメモ．

チェックイン済のチェックポイントが，特定の時間になるとチェックイン済一覧から消えてしまう，というのはまずい．そこで，チェックイン済のチェックポイントについては，表示時間帯・非表示時間帯とは無関係に，チェックイン済一覧へ常に表示する．

「地図上にチェックポイントがマーカー表示されているのに，チェックポイント候補一覧にない」
「チェックポイント候補一覧にリストされているが，地図上にマーカーが表示されていない」
はいずれも不自然なので，これらは常に連動して表示・非表示が制御されている必要がある．

チェックイン後に表示されるクイズは，描画時間帯とは違う可能性あり？
例えば，

（10時開始のチアリ―ティング部のパフォーマンスに誘導するため，15分前から描画し誘導をかける．）
→会場へ移動→パフォーマンスを見る→終了時刻11時直前の最後に見た決め技をクイズで解答

というフローの場合，描画はパフォーマンスがスタートした時間（10時頃）に終わらせるのがよさそう．
そうしないと，「誘導されて行ってみたら，パフォーンマンスが終わってた！」という状況になる可能性がある．

一方，クイズは，パフォーマンスを最後まで見ることで初めて，正解できるものになっている可能性がある．
こうした点で，時間のコントロールをどう決めるか確認要．

**Comment by yuu-nkjm** [comment]
@reikohishiyama まとめをありがとうございます． ちなみに投稿枠の右上の鉛筆マークを押すと編集ができます．

強調表示がなく，表示と非表示だけであれば，表示時間帯だけを与えるようにします．
 - 表示時間帯指定なし：ずっと表示
 - 表示時間帯指定あり：指定時間帯は表示
サーバサイドでやるのが簡単ですが，細かいコントロールが必要ならば，クライアントサイドでやらないとだめですね．

**Comment by reikohishiyama** [comment]
@yuu-nkjm ありがとうございます．了解しましたー．

表示時間だけを与える，
実際のプログラム（番組）の情報をテキストにする，
で了解しました．
この方向で決定にしたいと思いますが，念のため再確認して明日再度，ここに書きます．

上の仕様としてJSON上で記述するとして，どのように記述を与えたらよいでしょうか？

**Comment by yuu-nkjm** [comment]
@reikohishiyama 
@ieiri0104 が言っていたように，checkpointとtaskの関係が1対1であるならば，
checkpointの属性として，``visibleTimeFrom``と``visibleTimeTo``を追加して下さい．

```json
  "checkpoints": [
    {
      "id":"cafeteria",
       "visibleTimeFrom":  "yyyy-mm-dd hh:mm:ss",
       "visibleTimeTo":  "yyyy-mm-dd hh:mm:ss"
    }
]
```

よろしくお願いします．

**Comment by reikohishiyama** [comment]
了解です．デフォルトで追加します．

**Comment by yuu-nkjm** [comment]
@ayakix 

以下の仕様でいかがでしょうか？

- visibleTimeFromとvisibleTimeToを指定
FromからToまで表示

- visibleTimeFromだけ指定
visibleTimeFromを過ぎたら表示

- visibleTimeToだけ指定
visibleTimeToまで表示

- 両方なし
常に表示

**Comment by ayakix** [comment]
@yuu-nkjm ありがとうございます。JSONにはfrom/toを追加しない場合があるということですよね。
仕様については、そちらで承知しました。

もし可能でしたら、サーバ側の処理の段階で、例えば、

* fromが空なら`2001/01/01 00:00:00`で上書き
* toが空なら`2099/12/31 23:59:59`で上書き

をして頂けると、クライアント側では、

```
visibleTimeFromとvisibleTimeToを指定
FromからToまで表示
```

の一つのロジックだけで済むので楽だったりします。
ただ、この処理をクライアント側ですることも当然出来ますので、そちらでもOKです。

**Comment by yuu-nkjm** [comment]
@ayakix さん
やっぱそうですよね．
クライアント側はなるべく実装がシンプルになる方が良いので，
サーバ側でFromとToが必ず指定されている状態にします．

**Comment by ayakix** [comment]
@yuu-nkjm ありがとうございます。助かりますー。
