### ISSUE TITLE
訪問済みチェックポイント一覧画面にて回答を表示

### ISSUE THREAD

**Issue by ayakix** [MAGCruise/magcruise-citywalk#80]
訪問済みチェックポイント一覧画面において、正答と回答を表示する

**Comment by ayakix** [comment]
![2016-10-03 22 37 08](https://cloud.githubusercontent.com/assets/907388/19039309/5976fe5a-89ba-11e6-9260-1f8052d1f3ca.png)

@reikohishiyama @yuu-nkjm @ieiri0104 上記の様に、訪問済みチェックポイント一覧において、問題、正答、回答を表示するようにしました。

**Comment by reikohishiyama** [comment]
@ayakix @yuu-nkjm @ieiri0104 ありがとうございます！

「お昼は激込み」「みんなで課題」の文字の下に，空白地帯があります．
ここに，何か，そのチェックポイントに関する解説文のようなものを，表示できる仕様になっていましたでしょうか．．．？？

**Comment by ayakix** [comment]
特に仕様にはありませんが、表示することは可能です。
各チェックポイントに解説文のテキストを入力して頂ければ表示します。
例えば、パラメータは、`description`や`introduction`等でしょうか。

**Comment by reikohishiyama** [comment]
ありがとうございます．
ここに何も表示されていないとスカスカした印象なので，短い解説を表示することを考えたいですね．

@ieiri0104 ここに何らかの短い解説を入れるとして，情報は集まりそうですか？　せいぜいMAX60字程度でしょうか？

見た目事例：
| ------ | お昼は激込み
|  写真  | 理工カフェテリアは理工のメインダイニングで，席数は　
|           | 約450席です．麺コーナーが充実しています．コンセン　　 　
| ------ | トがある壁際のソファ席は人気があります．

**Comment by reikohishiyama** [comment]
@yuu-nkjm @ayakix 　JSON上で，description  として追加して問題ないでしょうか？
字数上のMAX制約ありますか？

  "checkpoints": [
    {
      "id":"cafeteria",
       "description":  "このカフェテリアは，学生の胃袋を満たしてくれます"
    }
]

**Comment by ayakix** [comment]
@reikohishiyama はい、問題ありません。基本的には、字数上のMAX制約はないです。
文字列をそのままHTMLに変換します。もし改行を挟みたい場合には`<br/>`としてください。

**Comment by ayakix** [comment]
@reikohishiyama @yuu-nkjm @ieiri0104 `description` を表示するようにしました。

@ieiri0104 or @reikohishiyama がJSONをアップデートし、 @yuu-nkjm がサーバプログラムを書き換えたら後に、このissueをクローズしてください。

![2016-10-08 20 59 11](https://cloud.githubusercontent.com/assets/907388/19212973/5cbcfb58-8d9a-11e6-8fea-57c74c939354.png)
