### ISSUE TITLE
位置情報ログの保存

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#82]
ここへ行く → コンパス表示中 の，位置情報取得の確認．

**Comment by yuu-nkjm** [comment]
@reikohishiyama @ieiri0104 

以下のログが取れます．

```
CREATED  : 記録日時秒
USER_ID  :
CHECKPOINT_GROUP_ID  
CHECKPOINT_ID : 目的としているチェックポイント
LAT  : 現在の緯度
LON  : 現在の経度
HEADING: 
```
@ayakix 
HEADINGですが，どのような角度と思えばよいのでしたっけ？

**Comment by ayakix** [comment]
`0<=HEADING<360`の値を取ります。
0:北
90:東
180:南
270:西
の時計回りとなっています。

**Comment by yuu-nkjm** [comment]
@ayakix 
(目的地などには関係なく)ユーザが北に向かって歩いているとき，0となるということですよね？

**Comment by ayakix** [comment]
@yuu-nkjm あ、失礼しました。仰る通りです。目的地に対しての角度ではありません。

**Comment by yuu-nkjm** [comment]
@ieiri0104 君，仕様通り取れているか確認し，取れていたらissue をcloseして下さい．

**Comment by yuu-nkjm** [comment]
@ayakix さん
coords.altitude, coords.accuracy や coords.speed など，取れるものは全て取っておこうかなとも思いますが，
どうでしょう？

**Comment by ayakix** [comment]
@yuu-nkjm 承知しました。私の方で付け足しておきおます。

**Comment by yuu-nkjm** [comment]
@ayakix 大きなデメリットがなければ，coords.speed, coords.altitudeAccuracy, coords.accuracy, coords.altitude など全部盛りでお願いしますm(_ _)m
