### ISSUE TITLE
早稲田祭2016の初期アクセス画面

### ISSUE THREAD

**Issue by reikohishiyama** [MAGCruise/magcruise-citywalk#85]
@yuu-nkjm @ieiri0104 @ayakix 
ログイン（スタート）画面について，以下のとおりです．

（これまで議論している内容）

ユーザにはひとまず
https://wasedasai.magcruise.org/
にアクセスしてもらうこととして，
実際には
https://wasedasai.magcruise.org/2016/
を起点にする．

https://wasedasai.magcruise.org/ から
https://wasedasai.magcruise.org/2016/app/
へはリダイレクトをかける．
QRコードが読み込めなかった時のために、URLも併記する．

***
本日，以下のことを確認しました．

■早稲田祭実行委員会で，以下にサイトのQRコードとURLを載せたい，との希望があった．
ビラ5,000枚
早稲田祭公式サイト
Snsへの投稿（事前2回，会期中1回）
パンフレット
立て看板×3枚
持ち看板×2枚

===================

上の準備をしたいので，印刷等準備のため，QRコードとURLを10月8日までに欲しい．

**:
当然ながら，現状で，早稲田祭にはQRコードとURLは提供していません．
以下の対応を考えますが，いかがでしょうか．

（１）データももらっておらず，検証・見極めができていないので，
　QRコードとURLの提供は，来週早くても1４日以降とする．
　（そもそも間に合わない場合は，上のような大々的な宣伝は，無くて何ら問題なし...）

（２）URL（QRコードも）は，https://wasedasai.magcruise.org/
を提供する予定とする．

（３）早稲田祭当日までは，
https://wasedasai.magcruise.org/ から
本番用の　https://wasedasai.magcruise.org/2016/app/
とは異なる（「開催準備中！」とだけ表示された）別なURL（←家入君HTMLちょうだい）へ
リダイレクトする．

（４）当日に
https://wasedasai.magcruise.org/ から
本番用の
https://wasedasai.magcruise.org/2016/app/
へのリダイレクトに，リダイレクト先へ切り替える．

**Comment by yuu-nkjm** [comment]
@ayakix 
トップページ(wasedasai.html)に「アプリの使い方」のような簡単な解説があると良いと思っていますが，
どんなこと書いたらいいですかね？

https://wasedasai.magcruise.org/2016/wasedasai.html

**Comment by ayakix** [comment]
@yuu-nkjm そうですねー。使い方って開発者が書くとわかりづらいんですよね。。。

こちら、 @ieiri0104 にお願いできますか？実際に使ってみて詰まったところを補足のような形で書いて頂けると助かります。（家入さんに理解できない部分は、ユーザーも理解できないと思うので。）

**Comment by ieiri0104** [comment]
@yuu-nkjm @ayakix 
了解いたしました。現地でのウォークスルーの際に、どこが補足すべきところかも探しながら、実験してみます。

**Comment by yuu-nkjm** [comment]
URL 構成を見直しました．```https://wasedasai.magcruise.org/2016/ => https://wasedasai.magcruise.org/magcruise-citywalk/```に変更します．

URLが長くなるのが嫌で短くしたのですが，人間が入れるとしたら
```https://wasedasai.magcruise.org/``` だけなので．

■公開URL (ユーザがQRコードないしは手入力するのはここ)
https://wasedasai.magcruise.org/

■アプリケーションルートURL (アプリケーションのルート)
https://wasedasai.magcruise.org/magcruise-citywalk/app/
