### ISSUE TITLE
ログアウト機能

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#87]
現在，ログアウトを押してもindex.htmlに戻るだけ．

- localStorageの掃除
- serverのlogout メソッドの呼び出しが必要．

**Comment by ayakix** [comment]
> localStorageの掃除

localStorageから消すのは、
city_walk_dataとcheckpoint_group_idですかね。

> serverのlogout メソッドの呼び出しが必要．

承知しました。

**Comment by yuu-nkjm** [comment]
@ayakix 
ログアウトと関係していると思うのですが，同一端末だと異なるIDでログインしても，
同じチェックポイント履歴が使われているようです．

つまり，user1でcheckpoint1にチェックインしたあとログアウト，同一端末でuser2でログインするとcheckpoint1がログイン済みになっているということです．

**Comment by ayakix** [comment]
@yuu-nkjm はい、おっしゃるとおりですね。訪問済みチェックポイントやタスクの回答はブラウザのローカルストレージで管理しているためです。
仕様どおりかとは思うのですが、こちら修正した方がよろしいでしょうか？

**Comment by yuu-nkjm** [comment]
@ayakix 
現在は，1端末1ユーザIDを想定しているということでしたっけ？

**Comment by ayakix** [comment]
@yuu-nkjm ですね。今はそのようになっております。確かに、実質ローカルデータを消さないので、ログアウトがただの遷移になりますね。

**Comment by yuu-nkjm** [comment]
-``localStrorage.userId``を操作するのは``register.html``だけ．
-``register.html``にアクセス出来るのは ``!getUserId()``が真のときだけ．それ以外は``login.html``に移動．
-``login.html``にアクセス出来るのは，``getUserId()``が真のときだけ．それ以外は``register.html``に移動

**Comment by ayakix** [comment]
基本的にログアウトはしないという感じになりそうですね。localStorageが壊れた/操作された系は仕方ないのかもしれません。
