### ISSUE TITLE
ランキング画面でのスコアの表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#91]
@ayakix 
ランキング画面でスコアを表示して欲しいです．scoreという属性を追加したので，その値を使って下さい．
https://i.gyazo.com/8dac14505e9ac44271287d0dc22f3942.png

ランキング画面などでも自分のユーザ名が見えた方が良いと思います．
#86

**Comment by ayakix** [comment]
![2016-10-08 8 28 58](https://cloud.githubusercontent.com/assets/907388/19208134/858c4318-8d31-11e6-9b2e-be8e1ec4fc01.png)

上のように表示しました。
また、チェックインを全くしていない状態ですと、rank`-1`をそのまま表示してしまっていたので、個人順位を表示しないようにしました。
