### ISSUE TITLE
カテゴリ名，サブカテゴリ名に日本語を使うと動かない

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#92]
@ayakix 
カテゴリ名，サブカテゴリ名に日本語を使うと表示されません．

URLパラメータ渡ししてるからですね．

![](https://i.gyazo.com/37aede1100b690d706c3a4835d075013.png)

**Comment by takawitter** [comment]
URLEncoder.encode(url, "UTF-8")/URLDecoder.decode(url, "UTF-8")で．
空白や一部記号も適切に処理してやる必要があるので，常にencode/decodeは意識した方が良いです．

**Comment by ayakix** [comment]
@yuu-nkjm 
ご指摘＆ご提案ありがとうございます。
念のため`encodeURIComponent`、`decodeURIComponent`にしておきました。

**Comment by yuu-nkjm** [comment]
@takawitter さん
いつもありがとうございます！ watchして下さってるんですね．
@ayakix さん
早速ありがとうございます！

**Comment by takawitter** [comment]
@yuu-nkjm メールが流れてくるので :-) 目が止まったものにたまにコメントしても問題ないですかね？

**Comment by yuu-nkjm** [comment]
@takawitter さん，むしろお願いします！
