### ISSUE TITLE
ランキングの表示

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#96]
@ayakix 

https://gyazo.com/8626aa860c7ac6e5bea4e8843fc88df2

あんまり起こらなそうですが，金，銀，銅の王冠が複数つくようなときの処理がおかしそうです．

```
1位，2位，2位，2位，5位
1位，1位，3位，4位
1位，2位，3位，3位
```

**Comment by ayakix** [comment]
@yuu-nkjm あ、同率順位ですね。失礼しました。修正します。

**Comment by ayakix** [comment]
というか、順位のソートが出来てなかったですね。こちらも修正します。

**Comment by ayakix** [comment]
@yuu-nkjm getRankingした際に、scoreによってrankが変動していなかったため、クライアント側でソートしました。（サーバ側のソースコードは見ていないのですが、0があるのでおそらく配列のindexになっている？）

その際に、同順も認めるようにしております。ex.) 1位，2位，2位，2位，5位

### ソート前
![2016-10-08 17 05 28](https://cloud.githubusercontent.com/assets/907388/19211553/3cf3ef90-8d7a-11e6-8ddf-5cd7038019d0.png)

### ソート後（同順可）
![2016-10-08 17 05 40](https://cloud.githubusercontent.com/assets/907388/19211561/602d0992-8d7a-11e6-8a54-2afce7c63011.png)


また、ユーザー名を右上に表示しております。
![2016-10-08 17 08 38](https://cloud.githubusercontent.com/assets/907388/19211577/a1cef02c-8d7a-11e6-8822-d35ce527f453.png)

**Comment by yuu-nkjm** [comment]
@ayakix 
サーバ側でソートしたつもりでした．しかもrankも配列のインデックス入れてただけでした．
+1しないといけないし，それこそ同点の処理を全然考えてなかったです．
