### ISSUE TITLE
チェックイン後にタスクをしなかった時に問題が起こる

### ISSUE THREAD

**Issue by yuu-nkjm** [MAGCruise/magcruise-citywalk#97]
@ayakix 
まず訪問済みチェックポイント表示でエラーが起こる．それは直せば良い．

でも，そもそもチェックイン後にタスクをしなかったときに，もうそのタスクができないというのはよくないっちゃよくない．taskindexを覚えておく？面倒？

**Comment by ayakix** [comment]
@yuu-nkjm https://github.com/MAGCruise/magcruise-citywalk/pull/99 こちらご確認願います。

**Comment by yuu-nkjm** [comment]
OKです！
